# -*- coding: utf-8 -*-
"""Legacy-audit follow-through, transaction LA-A: correct our own copy (public-risk fixes). English and Arabic together.

  python3 la_a_corrections.py <in_master.xlsx> <out_master.xlsx> <ledger.json> <work_dir>

Owner brief "Legacy-audit follow-through" of 10 October 2026, transaction A, with the owner's corrections of the same day
(audit/OWNER_DECISIONS_2026-10-10.md, addendum). Every locator below was read in the original by this session on
10 October 2026 (audit/legacy_followthrough/SOURCE_VERIFICATION_2026-10-10.md), not copied from the brief.

DIV-01  The FMIIP access-point definition IS published: the project appraisal document (Report No. PADHI00396, 22 May
        2025), Annex 1 (monitoring and evaluation plan), printed p. 26 (PDF p. 36): "the sum of (1) the number of branches
        of commercial banks and licensed Electronic Money Institutions; (2) the number of active agents of licensed
        financial institutions; (3) the number of in-service ATMs of commercial banks; and (4) the number of POS terminals
        accepting electronic payments". No de-duplication rule appears anywhere in the document. Every place that said the
        evidence base does not document the definition now says what it is and what is still not published.
DIV-02  The project's "active" definitions ARE published (same annex, printed p. 28, PDF p. 38): an active e-wallet
        account has been "used to perform at least one financial transaction within the last 90 days"; an active bank
        account is a current account with one transaction "within at least one year". CBY-Aden publishes no definition of
        a "subscriber" (H1-2025 payments infographic, read 10 October 2026). The four "definitions the evidence base does
        not document" sentences are split accordingly. The bank pair is added where the note stands: 5,202,019 accounts
        (CBY-Aden, first half of 2025; observation OBS-00037; infographic panel "Accounts", tile "NO. of Accounts") and
        1,062,441 active bank accounts (FMIIP, January 2025; PAD Annex 1, printed p. 24): different unit, universe and
        date; no ratio is published or implied. 5,202,019 is bound to CLM-010 (whose sources include the infographic and
        whose routes are /payments/, /reforms/ and /evidence/compare/); 90 is bound to FMIIP-BASELINE-2025-01.
DIV-03  SRC-LIT-XIDIAN-YEM-FI-2025 feeds no claim and its venue is flagged as hijacked (LIT-YEM-2025-005): it is set
        non-public (its address moves to the non-public locator note, so nothing is lost) and leaves /data/.
DIV-04  SRC-CCY-PRESSURE-2026 (a user-supplied file with no publisher) is unbound from CLM-045, so it no longer reaches
        CWR-010 through EP-YEM-CASH-FIN-TRANSMISSION-K04; the source-reference closure is regenerated by the runner.
OWN-2a  CLM-026's Arabic summary said "six of its measures — rather, three"; the English says three. Fixed.
"""
import json, os, sys
from collections import OrderedDict

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "tranche_c"))
from tc_lib import Session, Table, TxError  # noqa: E402

S03 = "03_PAGE_SECTIONS"
PAD = "SRC-WB-FMIIP-P180708"
INFO = "SRC-CBY-PAYREPORT-H1-2025"


def rep(s, finding, sheet, row, col, old, new):
    s.replace(finding, sheet, row, col, old, new, f"{sheet}!r{row}c{col}")


def tset(s, t, finding, key, field, old_sub, new_sub):
    cur = t.get(key, field)
    if not isinstance(cur, str) or cur.count(old_sub) != 1:
        raise TxError(f"{finding}: {t.sheet} {key}.{field}: {old_sub[:60]!r} occurs {0 if not isinstance(cur, str) else cur.count(old_sub)} times")
    t.set(finding, key, field, cur.replace(old_sub, new_sub), cur)


def add_values(s, t, finding, key, entries):
    cur = t.get(key, "value_states")
    vs = json.loads(cur or "[]")
    have = {v.get("t") for v in vs}
    for e in entries:
        if e["t"] in have:
            raise TxError(f"{finding}: {key} already carries value {e['t']!r}")
        vs.append(e)
    t.set(finding, key, "value_states", json.dumps(vs, ensure_ascii=False, separators=(",", ":")), cur)


# --------------------------------------------------------------------------------------------- DIV-01 access points
D1 = "LA-A:DIV-01"
D1_CWR003_EN_OLD = ("Nor can it be added to, or compared directly with, counts of ATMs, POS terminals or agents unless the "
                    "project’s access-point definitions and de-duplication rules are documented, and in the evidence base they are not.")
D1_CWR003_EN_NEW = ("The project’s appraisal document defines this access-point count, in its monitoring and evaluation annex, as the sum of the branches of commercial "
                    "banks and licensed e-money institutions, the active agents of licensed financial institutions, in-service ATMs "
                    "and POS terminals that accept electronic payments. It does not publish how each component is counted or any "
                    "rule for removing duplicates, so the total cannot be added to, or compared directly with, separate counts of "
                    "ATMs, POS terminals or agents.")
D1_CWR003_AR_OLD = ("ولا يجوز جمعه مع أعداد أجهزة الصراف الآلي أو نقاط البيع أو الوكلاء، أو مقارنته بها مباشرة، ما لم تُوثَّق تعريفات "
                    "المشروع لنقاط الوصول وقواعد إزالة الازدواج، وهي غير موثقة في قاعدة الأدلة.")
D1_CWR003_AR_NEW = ("وتعرّف وثيقة تقييم المشروع، في ملحق المتابعة والتقييم، هذا العدد من نقاط الوصول المالي بأنه مجموع فروع البنوك التجارية ومؤسسات النقود "
                    "الإلكترونية المرخصة، والوكلاء النشطين للمؤسسات المالية المرخصة، وأجهزة الصراف الآلي العاملة، وأجهزة نقاط البيع "
                    "التي تقبل المدفوعات الإلكترونية. لكنها لا تنشر طريقة عدّ كل مكوّن ولا أي قاعدة لإزالة الازدواج، لذلك لا يجوز "
                    "جمع هذا المجموع مع أعداد منفصلة لأجهزة الصراف الآلي أو نقاط البيع أو الوكلاء، ولا مقارنته بها مباشرة.")
D1_ACCESS_EN = ("under a project definition that the evidence base does not document.",
                "under the project’s own definition: the sum of bank and e-money-institution branches, active agents, in-service "
                "ATMs and POS terminals, with no published rule for removing duplicates.")
D1_ACCESS_AR = ("وفق تعريف للمشروع لا توثقه قاعدة الأدلة.",
                "وفق تعريف المشروع نفسه: مجموع فروع البنوك ومؤسسات النقود الإلكترونية، والوكلاء النشطين، وأجهزة الصراف الآلي "
                "العاملة، وأجهزة نقاط البيع، من دون قاعدة منشورة لإزالة الازدواج.")
D1_XW = {
    "summary_en": (" unless the project's access-point definitions and deduplication rules are documented.",
                   ": the project defines access points as the sum of four components and publishes no rule for removing duplicates."),
    "summary_ar": ("، ما لم تُوثَّق تعريفات المشروع لنقاط الوصول وقواعد إزالة الازدواج.",
                   "؛ إذ يعرّف المشروع نقاط الوصول بأنها مجموع أربعة مكوّنات، ولا ينشر قاعدة لإزالة الازدواج."),
    "method_en": ("because the project's access-point definitions and deduplication rules are not documented in the evidence base, "
                  "no combined or comparable figure is produced.",
                  "because the project defines its access points as the sum of bank and e-money-institution branches, active "
                  "agents, in-service ATMs and POS terminals (appraisal document, monitoring and evaluation annex) but publishes neither how each "
                  "component is counted nor any rule for removing duplicates, no combined or comparable figure is produced."),
    "method_ar": ("ولأن تعريفات المشروع لنقاط الوصول وقواعد إزالة الازدواج غير موثقة في قاعدة الأدلة، لا يُنتَج أي رقم مجمّع أو قابل للمقارنة.",
                  "ولأن المشروع يعرّف نقاط الوصول بأنها مجموع فروع البنوك ومؤسسات النقود الإلكترونية والوكلاء النشطين وأجهزة "
                  "الصراف الآلي العاملة وأجهزة نقاط البيع (وثيقة تقييم المشروع، ملحق المتابعة والتقييم)، من دون أن ينشر طريقة "
                  "عدّ كل مكوّن ولا أي قاعدة لإزالة الازدواج، لا يُنتَج أي رقم مجمّع أو قابل للمقارنة."),
}
D1_FMIIP_UNIVERSE = {
    "universe_en": ("The definitions and reporting scope behind each baseline are the project's own and are not documented in the evidence base.",
                    "Each indicator is defined by the project in its appraisal document (monitoring and evaluation annex); the counting rules and "
                    "reporting scope behind each baseline, such as any removal of duplicates, are not published."),
    "universe_ar": ("وتعريفات كل خط أساس ونطاق الإبلاغ الخاص به تعود إلى المشروع نفسه، ولا توثقها قاعدة الأدلة.",
                    "ويعرّف المشروع كل مؤشر في وثيقة تقييمه (ملحق المتابعة والتقييم)، لكن قواعد العدّ ونطاق الإبلاغ اللذين يستند "
                    "إليهما كل خط أساس، ومنها أي إزالة للازدواج، غير منشورة."),
}
D1_RV003 = {
    20: ("until the project's taxonomy and deduplication rules are documented.",          # 11 accessible_summary_en (col U)
         "because the project defines the total as the sum of four components and publishes no rule for removing duplicates."),
    21: ("ما لم تُوثق تصنيفات المشروع وقواعد إزالة الازدواج.",                              # 11 accessible_summary_ar (col V)
         "لأن المشروع يعرّف المجموع بأنه حاصل جمع أربعة مكوّنات، ولا ينشر قاعدة لإزالة الازدواج."),
}

# --------------------------------------------------------------------------------------------- DIV-02 "active" and subscribers
D2 = "LA-A:DIV-02"
OLD2_EN = ("The two carry different labels under definitions the evidence base does not document and that have not been "
           "reconciled, so the gap cannot be read as growth, as inactivity or as an error, and neither is a count of people.")
OLD2_AR = ("ويحمل الرقمان تسميتين مختلفتين وفق تعريفين لا توثقهما قاعدة الأدلة ولم يُطابَق بينهما؛ لذلك لا يُقرأ الفرق بينهما "
           "نموًا ولا خمولًا ولا خطأً، ولا يمثل أيٌّ منهما عددًا من الأشخاص.")
NEW2_EN = ("The project defines an active e-wallet account as one used for at least one financial transaction in the last 90 "
           "days; the CBY-Aden payments infographic for the first half of 2025 gives no definition of a subscriber. The two have "
           "not been reconciled, so the gap cannot be read as growth, as inactivity or as an error, and neither is a count of people.")
NEW2_AR = ("ويعرّف المشروع حساب المحفظة الإلكترونية النشط بأنه حساب استُخدم في معاملة مالية واحدة على الأقل خلال آخر 90 "
           "يومًا، بينما لا يقدّم إنفوغرافيك المدفوعات للنصف الأول من 2025 الصادر عن البنك المركزي اليمني – عدن تعريفًا للمشترك. "
           "ولم يُطابَق بين الرقمين؛ لذلك لا يُقرأ الفرق بينهما نموًا ولا خمولًا ولا خطأً، ولا يمثل أيٌّ منهما عددًا من الأشخاص.")
# CLM-010 is also shown on /providers/, where FMIIP is not a bound source: its own note names no number of days
NEW2_EN_CLM010 = ("The project publishes its own definition of an active e-wallet account; the CBY-Aden payments infographic for the "
                  "first half of 2025 gives no definition of a subscriber. The two have not been reconciled, so the gap cannot be read "
                  "as growth, as inactivity or as an error, and neither is a count of people.")
NEW2_AR_CLM010 = ("وينشر المشروع تعريفه الخاص لحساب المحفظة الإلكترونية النشط، بينما لا يقدّم إنفوغرافيك المدفوعات للنصف الأول من 2025 "
                  "الصادر عن البنك المركزي اليمني – عدن تعريفًا للمشترك. ولم يُطابَق بين الرقمين؛ لذلك لا يُقرأ الفرق بينهما نموًا ولا "
                  "خمولًا ولا خطأً، ولا يمثل أيٌّ منهما عددًا من الأشخاص.")
BANK_EN = (" Likewise, CBY-Aden reports 5,202,019 accounts for the first half of 2025, while the project counts 1,062,441 active "
           "bank accounts in January 2025 — current accounts with at least one transaction in a year. The two differ in unit, "
           "universe and date, and no ratio between them is published or implied.")
BANK_AR = (" وبالمثل، يُبلغ البنك المركزي اليمني – عدن عن 5,202,019 حسابًا للنصف الأول من 2025، بينما يحصي المشروع 1,062,441 "
           "حسابًا مصرفيًا نشطًا في يناير 2025، أي حسابات جارية أُجريت عليها معاملة واحدة على الأقل خلال سنة. ويختلف الرقمان في "
           "الوحدة والمجتمع والتاريخ، ولا تُنشر بينهما أي نسبة، صراحةً أو ضمنًا.")
CLM010_BANK_EN = (" The same CBY-Aden infographic reports 5,202,019 accounts for the first half of 2025 — a count of accounts in "
                  "its reporting scope, under no published definition, not of people.")
CLM010_BANK_AR = (" ويورد الإنفوغرافيك نفسه الصادر عن البنك المركزي اليمني – عدن 5,202,019 حسابًا للنصف الأول من 2025، وهو عدد "
                  "للحسابات ضمن نطاق إبلاغه ومن دون تعريف منشور، لا عدد للأشخاص.")
COMPARE_BANK_EN = (" Separately, CBY-Aden reports 5,202,019 accounts for the first half of 2025: a different unit, universe and "
                   "date from the active bank accounts in the project's baseline, and no ratio between them is published or implied.")
COMPARE_BANK_AR = (" وبصورة منفصلة، يُبلغ البنك المركزي اليمني – عدن عن 5,202,019 حسابًا للنصف الأول من 2025، ويختلف هذا الرقم في "
                   "الوحدة والمجتمع والتاريخ عن الحسابات المصرفية النشطة في خط أساس المشروع، ولا تُنشر بينهما أي نسبة، صراحةً أو ضمنًا.")

# --------------------------------------------------------------------------------------------- OWN-2a CLM-026 Arabic
F26 = "LA-A:OWN-2a"
CLM026_OLD = "وأصبحت لـسـتة من مقاييسها — بل لـثلاثة منها — قيم منشورة لموجة 2021"
CLM026_NEW = "وأصبحت لثلاثة من مقاييسها قيم منشورة لموجة 2021"


def main():
    src, out, ledger, work = sys.argv[1:5]
    s = Session(src, work)
    t06 = Table(s, "06_EVIDENCE_OBJECTS")
    t11 = Table(s, "11_VISUAL_LIBRARY")
    t15 = Table(s, "15_SOURCE_LIBRARY")

    # DIV-01
    rep(s, D1, S03, s.section_row("/readings/define-what-you-count/", 5, "en"), 5, D1_CWR003_EN_OLD, D1_CWR003_EN_NEW)
    rep(s, D1, S03, s.section_row("/readings/define-what-you-count/", 5, "ar"), 7, D1_CWR003_AR_OLD, D1_CWR003_AR_NEW)
    rep(s, D1, S03, s.section_row("/access/", 3, "en"), 5, *D1_ACCESS_EN)
    rep(s, D1, S03, s.section_row("/access/", 3, "ar"), 7, *D1_ACCESS_AR)
    for field, (o, n) in D1_XW.items():
        tset(s, t06, D1, "XW-FMIIP-005", field, o, n)
    for field, (o, n) in D1_FMIIP_UNIVERSE.items():
        tset(s, t06, D1, "FMIIP-BASELINE-2025-01", field, o, n)
    tset(s, t11, D1, "RV-CWR-003", "accessible_summary_en", *D1_RV003[20])
    tset(s, t11, D1, "RV-CWR-003", "accessible_summary_ar", *D1_RV003[21])

    # DIV-02: the four notes, then the bank pair where the note stands
    for route, order in (("/payments/", 5), ("/reforms/", 6)):
        rep(s, D2, S03, s.section_row(route, order, "en"), 5, OLD2_EN, NEW2_EN + BANK_EN)
        rep(s, D2, S03, s.section_row(route, order, "ar"), 7, OLD2_AR, NEW2_AR + BANK_AR)
    tset(s, t06, D2, "FMIIP-BASELINE-2025-01", "limitations_en", OLD2_EN, NEW2_EN)
    tset(s, t06, D2, "FMIIP-BASELINE-2025-01", "limitations_ar", OLD2_AR, NEW2_AR)
    tset(s, t06, D2, "CLM-010", "limitations_en", OLD2_EN, NEW2_EN_CLM010 + CLM010_BANK_EN)
    tset(s, t06, D2, "CLM-010", "limitations_ar", OLD2_AR, NEW2_AR_CLM010 + CLM010_BANK_AR)
    rep(s, D2, S03, s.section_row("/evidence/compare/", 2, "en"), 5,
        "accounts, not people.", "accounts, not people." + COMPARE_BANK_EN)
    rep(s, D2, S03, s.section_row("/evidence/compare/", 2, "ar"), 7,
        "أي حسابات لا أشخاص.", "أي حسابات لا أشخاص." + COMPARE_BANK_AR)
    add_values(s, t06, D2, "FMIIP-BASELINE-2025-01", [
        {"t": "90", "k": "v", "s": "READ", "src": PAD,
         "loc": "PAD (Report No. PADHI00396, 22 May 2025), Annex 1, printed p. 28 (PDF p. 38): active e-wallet accounts \"used to perform at least one financial transaction within the last 90 days\"; active bank accounts: one transaction \"within at least one year\" (current accounts); read 10 October 2026"}])
    add_values(s, t06, D2, "CLM-010", [
        {"t": "5,202,019", "k": "v", "s": "READ", "src": INFO,
         "loc": "CBY-Aden First Half Payment Report (2025) infographic, panel \"Accounts\", tile \"NO. of Accounts\" (observation OBS-00037); no definition of account or subscriber is given; read 10 October 2026"}])

    # DIV-03: the hijacked-venue paper leaves the public directory; its address is kept in the non-public note
    url = t15.get("SRC-LIT-XIDIAN-YEM-FI-2025", "primary_url")
    if not str(url or "").startswith("https://www.researchgate.net/"):
        raise TxError(f"LA-A:DIV-03: unexpected primary_url {url!r}")
    t15.set("LA-A:DIV-03", "SRC-LIT-XIDIAN-YEM-FI-2025", "primary_url", None, url)
    t15.set("LA-A:DIV-03", "SRC-LIT-XIDIAN-YEM-FI-2025", "non_public_locator_note",
            "NON_PUBLIC (legacy-audit DIV-03, 10 October 2026): publication venue flagged as a hijacked journal domain "
            "(LIT-YEM-2025-005); feeds no claim; withheld from the public directory. Address: " + url, None)

    # DIV-04: the user-supplied file no longer reaches CLM-045 (and so CWR-010)
    tset(s, t06, "LA-A:DIV-04", "CLM-045", "source_dependencies", "SRC-CCY-PRESSURE-2026; ", "")

    # OWN-2a
    tset(s, t06, F26, "CLM-026", "summary_ar", CLM026_OLD, CLM026_NEW)

    r = s.save(out, ledger, OrderedDict([
        ("transaction", "LA-A"),
        ("summary", "Legacy-audit follow-through A: access-point and 'active' definitions documented; the bank pair; the hijacked-venue "
                    "source made non-public; the user-supplied file unbound from CLM-045; CLM-026's Arabic fixed")]))
    print(json.dumps({k: r[k] for k in ("input_master_sha256", "output_master_sha256", "cells_written")}))


if __name__ == "__main__":
    try:
        main()
    except TxError as ex:
        print("TX ERROR:", ex)
        sys.exit(2)
