#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""design/02_TOKENS.json is generated from the reference stylesheet (design/reference/yfie/theme.py): the :root custom
properties, their Arabic and wide-screen overrides, and the roles the Lock gives them.

  python3 design/reference/tokens.py            # regenerate design/02_TOKENS.json
  python3 design/reference/tokens.py --check    # exit 1 if the committed file differs from the stylesheet
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "design/reference"))
from yfie import theme  # noqa: E402

OUT = ROOT / "design/02_TOKENS.json"

ROLES = {
    "--paper": "surface of objects and the page", "--plaster": "surface of figure insets and the institutional band",
    "--ink": "text; heavy rules at the start of an object", "--ink-2": "secondary text, captions, chart annotation",
    "--mute": "labels on paper (never on plaster)", "--rule": "hairline between answers", "--rule-2": "hairline in the spine and tables; stems",
    "--ochre": "rubrics and the figure-group line (from the logo)", "--ochre-line": "the ochre hairline",
    "--counter": "the boundary voice and the not-comparable divider (from the logo)",
    "--fs-body": "body", "--lh-body": "body leading", "--fs-display": "display (h1)", "--lh-display": "display leading",
    "--fs-q": "question and section heading", "--lh-q": "question leading", "--fs-st": "statement (first answer, thesis)",
    "--lh-st": "statement leading", "--fs-bnd": "boundary voice", "--lh-bnd": "boundary leading",
    "--fs-clock": "clock, reference, chart annotation", "--lh-clock": "clock leading", "--fs-rubric": "rubric",
    "--fs-src": "source, citation, small", "--lh-src": "source leading", "--fs-nav": "navigation", "--fs-read": "Reading body",
    "--lh-read": "Reading body leading", "--measure": "text measure", "--font": "family",
}


def block(css: str, selector: str) -> dict:
    m = re.search(re.escape(selector) + r"\{([^}]*)\}", css)
    if not m:
        return {}
    out = {}
    for decl in m.group(1).split(";"):
        if ":" in decl:
            k, v = decl.split(":", 1)
            out[k.strip()] = v.strip()
    return out


def tokens(d: dict) -> dict:
    return {k: {"value": v, "role": ROLES.get(k, "")} for k, v in d.items()}


def generate() -> dict:
    css = theme.CSS
    root, rtl = block(css, ":root"), block(css, "html[dir=rtl]")
    wide = re.search(r"@media \(min-width:900px\)\{(.*?)\n\}\n", css, re.S).group(1)
    droot, drtl = block(wide, ":root"), block(wide, "html[dir=rtl]")
    is_type = lambda k: k.startswith(("--fs", "--lh", "--measure", "--font"))
    return {
        "about": "D1 foundational grammar — generated by design/reference/tokens.py from design/reference/yfie/theme.py (the reference stylesheet's custom properties) after the reference implementation of the stress trio. Technology-neutral (CSS custom properties, no framework). Governed by the Design Intent Lock (design/01_FOUNDATIONS.md §4): values may move at D2+ within the Lock; roles do not.",
        "status": "D4 — proven on every one of the 288 documents (the stress trio at D1, the hard families at D2, the synthesis pages at D3, every evidence record and the remaining domain answers at D4) in English and Arabic at 320–1440 px; every document builds from the same stylesheet (theme.CSS + theme.CSS_D2)",
        "identity": {
            "logo": "site-src/assets/CauseWay_Master_Logo.png (unaltered; EAD-04)",
            "fonts": {"latin": "IBM Plex Sans (Light 300, Regular 400, Italic 400, Medium 500, SemiBold 600, Bold 700), self-hosted from vendor/fonts/ibm-plex-sans",
                      "arabic": "IBM Plex Sans Arabic (Light 300, Regular 400, Medium 500, SemiBold 600, Bold 700), self-hosted from vendor/fonts/ibm-plex-sans-arabic"},
            "digits": "Western in both languages, as governed copy; numeric runs, IDs and ISO dates isolated left-to-right (bdi) and unbroken",
        },
        "colour": {k: v for k, v in tokens(root).items() if not is_type(k)},
        "type": {
            "latin": {"narrow": {k: v for k, v in tokens(root).items() if is_type(k)}, "wide (≥900px)": tokens(droot)},
            "arabic": {"narrow": tokens(rtl), "wide (≥900px)": tokens(drtl)},
            "weights": {"display": 600, "question": 400, "statement (first answer, thesis)": 500, "boundary": 500, "resolution": 600, "rubric": 600, "clock label": 600, "clock value": 600, "body": 400, "source title": 600},
            "rules": {"Latin rubric": "uppercase, letter-spacing .1em", "Arabic rubric": "weight and colour only; no letter-spacing, no capitals mimicry", "h1": "text-wrap: balance; Latin letter-spacing -.012em", "numerals": "tabular-nums throughout"},
        },
        "rules": {"hairline": "1px var(--rule) between answers; 1px var(--rule-2) in the spine and tables", "object start": "3px solid var(--ink)", "boundary": "3px double var(--counter)",
                  "figure inset": "3px solid var(--ink) top on var(--plaster)", "institutional band": "3px solid var(--ink) top on var(--plaster)"},
        "space": {"page gutter narrow": "16px", "page gutter wide": "32px", "object gap narrow": "14px", "object gap wide": "18–22px", "answer padding-top": "14–16px", "compact object padding": "14–16px 0",
                  "hit area": "≥40px rows in the index and spine; ≥44px product-bar controls; ≥24px in-flow actions"},
        "layout": {"breakpoints": {"600": "narrow index in two columns; figure lanes side by side; panel-1 row labels beside their tracks", "900": "spine column (280px) beside the object; product-bar navigation visible; menu hidden; the foot spine hidden", "1200": "rubric column (220px) beside each answer; spine 300px"},
                   "measure": {"latin": root.get("--measure", ""), "arabic": rtl.get("--measure", "")}, "max page width": "1240px", "object max width (wide)": "840px",
                   "sticky spine": "top 20px, max-height calc(100vh - 40px), overflow auto"},
        "focus": {"visible": "3px double var(--counter), offset 3px", "skip link": "first focusable; shown on focus at top-start"},
        "motion": "none by design; prefers-reduced-motion honoured (no transitions or animations anywhere)",
        "analytical states": {"observed / reported": "value with its governed state label in tables; ● □ ◎ marks keyed by publication, never by colour", "derived": "labelled 'Calculated here from published figures' (governed)",
                              "boundary": "the boundary voice", "not comparable": "double rule between lanes with the governed label", "missing": "never drawn as zero; no chart invented where a contract has no data"},
        "print": "product-bar controls, dialog, indexes and footer link groups removed; objects and figures kept whole; the record's disclosure content printed; source locators and the canonical link printed after their text; page breaks avoided inside objects",
    }


def main() -> int:
    data = generate()
    text = json.dumps(data, ensure_ascii=False, indent=1) + "\n"
    if "--check" in sys.argv:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        ok = current == text
        print("TOKENS CURRENT" if ok else "TOKENS STALE: run python3 design/reference/tokens.py")
        return 0 if ok else 1
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}: {len(data['colour'])} colour tokens, {len(data['type']['latin']['narrow'])} Latin type tokens")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
