#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""The host headers of `_headers`, as an nginx server block, for the DigitalOcean release route (owner decision of
3 October 2026: production hosting is DigitalOcean, at https://causewaygrp.com/financial-inclusion-evidence/).

  python3 scripts/hosting_nginx.py --site build/site --out build/do/default.conf             # the deployed block
  python3 scripts/hosting_nginx.py --site build/site --out x.conf --listen 127.0.0.1:8099 \\
      --root /tmp/www --local-http                                                          # the local proof

`_headers` (site-src/hosting/_headers, relocated under the base path by `scripts/build.py --out`) stays the one header
contract: the format Cloudflare Pages and Netlify read, and the file `scripts/tests/test_security_headers.py` serves
`dist/` with. A DigitalOcean App Platform static-site component cannot send custom response headers
(docs/RELEASE_RUNBOOK.md, "Hosting"), so the release route serves the published site from nginx — in an App Platform
service built from site-src/hosting/digitalocean/Dockerfile, or on a Droplet — and this script writes that nginx
configuration from `_headers`, so the two can never drift. `scripts/tests/test_digitalocean_hosting.py` runs it in a
real nginx and loads every page through the existing header test.

What the block does:
- every `_headers` path rule becomes one location: an exact path (`location =`), or a trailing-`*` prefix
  (`location ^~`). nginx does not inherit `add_header` into a location that sets its own, so each location carries the
  site-wide rule (`<base>/*`) and its own rule, in full, with `always` (a 404 or a redirect carries them too);
- the bare base path answers one permanent redirect to the path with its slash; a directory without its slash
  answers nginx's own 301; both with a relative `Location` (`absolute_redirect off`), so no upstream host name leaks
  through a proxy;
- a missing page answers the site's own 404 page with status 404; anything outside the base path answers 404;
- `server_tokens off`; no cookie, no `X-Robots-Tag` and no `X-Powered-By` is ever written.
`--local-http` drops `upgrade-insecure-requests` from the policy, and only for a plain-HTTP local proof, exactly as the
local header test does; the deployed block is never written with it.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts" / "tests"))
from test_security_headers import parse_headers  # noqa: E402  the one parser of the header contract


def _quote(value: str) -> str:
    if "$" in value or "\n" in value:
        raise SystemExit(f"_headers: a value nginx would interpolate or split: {value!r}")
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def server_block(headers_text: str, base: str, listen: str = "8080", root: str = "/usr/share/nginx/html",
                 local_http: bool = False) -> str:
    rules = parse_headers(headers_text)
    site_wide = base + "/*"
    glob = [hs for p, hs in rules if p == site_wide]
    if len(glob) != 1:
        raise SystemExit(f"_headers: expected exactly one site-wide rule {site_wide!r}")
    glob_h = glob[0]

    def directives(own):
        out = []
        for name, value in [*glob_h, *own]:
            if local_http and name == "Content-Security-Policy":
                value = "; ".join(d for d in (x.strip() for x in value.split(";")) if d and d != "upgrade-insecure-requests")
            if name.lower() in ("set-cookie", "x-robots-tag", "x-powered-by"):
                raise SystemExit(f"_headers: {name} must never be sent")
            out.append(f"        add_header {name} {_quote(value)} always;")
        return "\n".join(out)

    blocks = []
    for pattern, hs in rules:
        if pattern == site_wide:
            continue
        if not pattern.startswith(base + "/"):
            raise SystemExit(f"_headers: {pattern!r} is outside the base path {base!r}")
        if "*" in pattern[:-1] or ("*" in pattern and not pattern.endswith("/*")):
            raise SystemExit(f"_headers: only a trailing '/*' is supported: {pattern!r}")
        loc = f"location ^~ {pattern[:-1]}" if pattern.endswith("*") else f"location = {pattern}"
        extra = "\n        types { }\n        default_type application/xml;" if pattern.endswith(".xml") else ""
        blocks.append(f"    {loc} {{{extra}\n{directives(hs)}\n    }}")
    bare = (f"    location = {base} {{\n{directives([])}\n        return 301 {base}/;\n    }}\n") if base else ""
    return (f"""# Generated by scripts/hosting_nginx.py from the published site's _headers; do not edit by hand.
server {{
    listen {listen};
    server_name _;
    server_tokens off;
    absolute_redirect off;
    root {root};
    index index.html;
    charset utf-8;
    charset_types text/css application/javascript application/json text/plain text/xml application/xml;
    error_page 404 {base}/404.html;

{bare}    location ^~ {base}/ {{
{directives([])}
    }}
""" + "\n".join(blocks) + ("""
    location / {
        return 404;
    }
""" if base else "\n") + "}\n")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--site", required=True, help="the published site, built by scripts/build.py --out")
    ap.add_argument("--out", required=True)
    ap.add_argument("--base", default=None, help="the base path; default: read from the site's _headers")
    ap.add_argument("--listen", default="8080")
    ap.add_argument("--root", default="/usr/share/nginx/html", help="the directory that holds <base>/")
    ap.add_argument("--local-http", action="store_true")
    a = ap.parse_args()
    text = (Path(a.site) / "_headers").read_text(encoding="utf-8")
    base = a.base
    if base is None:
        m = re.search(r"^(/[^\s*]*?)/\*\s*$", text, re.M)
        base = m.group(1) if m else ""
    Path(a.out).parent.mkdir(parents=True, exist_ok=True)
    Path(a.out).write_text(server_block(text, base, a.listen, a.root, a.local_http), encoding="utf-8")
    print(f"NGINX SERVER BLOCK: {a.out} (base {base or '/'}, listen {a.listen})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
