# -*- coding: utf-8 -*-
"""Write or check FINAL_REPOSITORY_MANIFEST.json: what every tracked file is, and the one path from authority to
recipient (R8.5, directive D7 §F4).

  python3 scripts/repository_manifest.py           # write
  python3 scripts/repository_manifest.py --check   # exit 1 if the committed manifest is stale or a file is unclassified

Hashes live in SHA256SUMS.txt (scripts/checksums.py); this manifest classifies. Every tracked file must match exactly
one class rule below, so a new file cannot enter the repository without being placed.
"""
import fnmatch, hashlib, json, sys
from collections import Counter, OrderedDict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "FINAL_REPOSITORY_MANIFEST.json"
MASTER = "authority/Yemen_Financial_Inclusion_Evidence_Master.xlsx"
SPECS = "site-src/content/page_specs.json"
LOGO = "site-src/assets/CauseWay_Master_Logo.png"

# (class, glob patterns) — first match wins; order runs from specific to general.
RULES = [
    ("AUTHORITY_MASTER", [MASTER]),
    ("AUTHORITY_RULES", ["authority/CORE_CONSTITUTION.md"]),
    ("AUTHORITY_POINTER", ["authority/AUTHORITY.json", "authority/YFI_CURRENT_PROJECT_CONTEXT.json"]),
    ("LOGO_AUTHORITY", [LOGO]),
    ("PROJECTION_GENERATOR", ["scripts/generate_projections.py", "scripts/rebind_authority.py", "scripts/projection/*.py",
                              "scripts/projection/README.md", "scripts/projection/tests/*.py"]),
    ("PROJECTION_CONTRACT", ["scripts/projection/master_structure.json", "scripts/projection/projection_manifest.json",
                             "scripts/projection/controlled_inputs/*"]),
    # Hand-maintained controlled contracts under site-src/content (steward-edited in place; validated by the generator)
    ("CONTROLLED_CONTRACT", ["site-src/content/presentation_priority.json", "site-src/content/content/navigation_interaction.json"]),
    ("GENERATED_PROJECTION", ["site-src/content/*", "site-src/content/**/*"]),
    # The governed social images (EAD-09): generated by scripts/social_images.py from the design's own template, and
    # committed like every other output this repository publishes, because rasterising them needs a browser.
    ("GENERATED_SOCIAL_IMAGES", ["site-src/assets/social/*"]),
    # The logo's web-size derivatives (EAD-03): pure resamples of the unchanged master by scripts/logo_derivatives.py,
    # whose --check proves it pixel for pixel; committed because the build stays standard-library only.
    ("GENERATED_LOGO_DERIVATIVES", ["site-src/assets/logo/*"]),
    ("RUNTIME_SOURCE", ["site-src/app.js", "site-src/lang-redirect.js", "site-src/deployment.json", "site-src/assets/*",
                        "site-src/hosting/*"]),   # B14 b: the host headers, copied unchanged into dist/
    # The one production renderer (EAD-01): the accepted Design implementation, promoted out of design/reference.
    # scripts/build.py drives it into dist/; design/reference/ builds *through* it and holds no renderer of its own.
    ("PRODUCTION_RENDERER", ["scripts/yfie/*.py"]),
    ("BUILD_AND_GATES", ["scripts/build.py", "scripts/validate.py", "scripts/audit_public_literals.py",
                         "scripts/architecture_diagrams.py", "scripts/checksums.py", "scripts/repository_manifest.py", "scripts/discovery.py", "scripts/base_path.py",
                         "scripts/handoff_inventory.py", "scripts/social_images.py", "scripts/logo_derivatives.py", "scripts/hosting_nginx.py", "scripts/do_deploy.py", "scripts/accessibility_audit.py",
                         "scripts/exports.py", "scripts/performance_budget.py", "scripts/currentness_rerun.py",
                         "scripts/literal_audit_allowances.json", "scripts/search_canonical_probe.json", "scripts/tests/*",
                         "scripts/hosting/*",   # R-09: the corporate proxy harness that scripts/tests/test_corporate_proxy.py runs
                         "audit/tranche_c/checks/*.py", "audit/pre_tranche_c/source_lineage_truth_test.py"]),
    ("GENERATED_PUBLIC_BUILD", ["dist/*", "dist/**/*"]),
    ("GENERATED_LITERAL_CLOSURE", ["audit/PUBLIC_LITERAL_CLOSURE.json"]),
    ("GENERATED_DIAGRAMS", ["design/architecture/*"]),
    ("DESIGN_PACKAGE", ["design/*", "design/**/*"]),          # Claude Design's package and reference implementation (R8.6)
    ("RECIPIENT_HANDOFF", ["handoff/*"]),
    ("VENDORED_FONTS", ["vendor/fonts/*", "vendor/fonts/**/*"]),   # IBM Plex woff2 + OFL licence, unchanged (F9)
    ("CURRENT_DOCUMENT", ["README.md", "CONTRIBUTING.md", "AGENTS.md", "CLAUDE.md", "OPENAI_REENTRY_CHECKPOINT.md",
                          "FINAL_OPEN_ITEMS_REGISTER.md", "docs/CHANGELOG.md", "docs/PRODUCTION_REPOSITORY_PROTOCOL.md",
                          "docs/DEPLOYMENT.md", "docs/SUSTAINABILITY_METHOD.md", "docs/SUSTAINABILITY_IMPLEMENTED_RUNTIME.json",
                          "docs/ACCESSIBILITY_AUDIT.md", "docs/ACCESSIBILITY_AUDIT.json"]),
    ("REPOSITORY_ENGINEERING", [".github/*", ".github/**/*", ".gitattributes", ".gitignore", "package.json", "package-lock.json",
                                "requirements.txt", "SHA256SUMS.txt"]),
    ("CURRENT_PROGRAMME_RECORD", ["audit/INDEX.md", "audit/READING_PORTFOLIO_*", "audit/F3_*", "audit/R8_5_*", "audit/F5_*",
                                  "audit/F6_*", "audit/R8_6_*", "audit/SUSTAINABILITY_*", "audit/FINAL_*_ACCEPTANCE*",
                                  "audit/directives/D7_*", "audit/directives/D8_*", "audit/directives/D9_*", "audit/directives/README.md", "audit/reading_integration/*", "audit/reading_integration/**/*",
                                  "audit/final_integration/*", "audit/final_integration/**/*",
                                  "audit/release_candidate/*", "audit/release_candidate/**/*",
                                  # The close-out programme (brief of 10 October 2026): its brief, progress and key migration,
                                  # and the adjudicated Arabic review with the OpenAI package as lineage. Never projected.
                                  "audit/close_out/*", "audit/close_out/**/*", "audit/arabic_review/*", "audit/arabic_review/**/*"]),
    ("STANDING_POLICY", ["audit/ARABIC_TERMINOLOGY_AND_STYLE_LEDGER.md", "audit/BENCHMARK_AND_COMPARATOR_POLICY.md",
                         "audit/ECONOMIC_CONTEXT_USAGE_POLICY.md", "audit/FINAL_CURRENTNESS_CUTOFF.md", "audit/tranche_c/DRAFTING_RULES.md",
                         "audit/naming/ARABIC_HOUSE_STYLE.md"]),   # D11: adopted under the Master terminology register
    ("AUDIT_HISTORY", ["audit/*", "audit/**/*", "docs/*"]),
]
START_PATH = ["README.md", "handoff/README_FIRST.md", "handoff/CLAUDE_DESIGN_MASTER_PROMPT.md"]


def sha(p):
    return hashlib.sha256((ROOT / p).read_bytes()).hexdigest()


def tracked():
    """The tracked files (git ls-files); in an extracted archive without .git, every file under the root except caches —
    the same file set scripts/checksums.py uses, so the manifest can be checked from the handoff ZIP (F9)."""
    sys.path.insert(0, str(ROOT / "scripts"))
    import checksums  # noqa: E402
    return sorted(p for p in checksums.tracked_files() if p and p != OUT.name)


def classify(path):
    for cls, pats in RULES:
        if any(fnmatch.fnmatchcase(path, p) for p in pats):
            return cls
    return None


def build():
    files = tracked()
    rows, unclassified = [], []
    for p in files:
        c = classify(p)
        (rows if c else unclassified).append((p, c))
    counts = Counter(c for _, c in rows)
    doc = OrderedDict([
        ("schema", "YFIE_FINAL_REPOSITORY_MANIFEST/1.0"),
        ("purpose", "What every tracked file is. One authority -> one projection path -> one runtime content path -> one current recipient start path. Hashes: SHA256SUMS.txt."),
        ("authority", OrderedDict([("production_master", MASTER), ("production_master_sha256", sha(MASTER)),
                                   ("page_specs", SPECS), ("page_specs_sha256", sha(SPECS)),
                                   ("logo", LOGO), ("logo_sha256", sha(LOGO)),
                                   ("rule", "The Production Master is the only semantic authority. Everything under site-src/content, dist, design/architecture and audit/PUBLIC_LITERAL_CLOSURE.json is generated from it and never edited by hand, except the two CONTROLLED_CONTRACT files, which the programme steward maintains in place and the generator validates against the Master's projections.")])),
        ("paths", OrderedDict([
            ("projection", "authority/…Master.xlsx -> scripts/generate_projections.py (scripts/projection/*, contracts: master_structure.json, projection_manifest.json, controlled_inputs/*) -> site-src/content/**"),
            ("runtime", "site-src/content/** + site-src/app.js + site-src/lang-redirect.js + site-src/assets/* + vendor/fonts/** -> scripts/yfie (the one renderer) <- scripts/build.py -> dist/**"),
            ("change", "Master transaction -> audit/tranche_b_execution/run_stage.py (generate, rebind, build, literal audit, diagrams, validate, --check) -> commit"),
            ("recipient_start", START_PATH),
        ])),
        ("class_counts", OrderedDict(sorted(counts.items()))),
        ("files", [OrderedDict([("path", p), ("class", c)]) for p, c in rows]),
    ])
    return doc, unclassified


def main():
    doc, unclassified = build()
    text = json.dumps(doc, ensure_ascii=False, indent=1) + "\n"
    if unclassified:
        print("UNCLASSIFIED FILES:", *[p for p, _ in unclassified], sep="\n  ")
        sys.exit(1)
    if "--check" in sys.argv:
        cur = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if cur != text:
            print("REPOSITORY MANIFEST STALE: run python3 scripts/repository_manifest.py and commit")
            sys.exit(1)
        print(f"REPOSITORY MANIFEST CURRENT: {len(doc['files'])} files in {len(doc['class_counts'])} classes")
        return
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"REPOSITORY MANIFEST WRITTEN: {len(doc['files'])} files in {len(doc['class_counts'])} classes")


if __name__ == "__main__":
    main()
