# -*- coding: utf-8 -*-
"""P2 — FALSE OR MATERIALLY MISLEADING PUBLIC STATEMENTS.
op=SUBSTR: exact old substring -> new text, applied in every Master cell that contains it
(optionally restricted by sheets / rows / fields). The builder verifies hit counts."""

VER_OECD = ("OECD/INFE (2023) International Survey of Adult Financial Literacy (15_SOURCE_LIBRARY SRC-OECD-INFE-2023), verified against the official report by the independent "
            "recipient-side review of Tranche B (acceptance correction A): Figure 2.1 Yemen overall financial-literacy score 42/100; Figure 4.1 Yemen financial well-being score 15/100; "
            "Annex A Yemen sample 1,000, fieldwork 11 March–1 April 2023, telephone and face-to-face collection; the coordinated 2022/23 financial-attitude score uses the two required "
            "attitude questions (the optional third is excluded). Corroborated by OECD (2026) Promoting Economic Resilience in Yemen (SRC-OECD-YEM-RESILIENCE-001), retained as Yemen "
            "analytical literature; the 2023 OECD/INFE report is the measurement authority. Introduction: Yemen data 'collected in the framework of technical assistance or regional projects'. "
            "No ranking is adopted (audit/BENCHMARK_AND_COMPARATOR_POLICY.md).")
FX = "SRC-CBY-001 is published on cby-ye.com, whose seat is verified as CBY-Aden in the project verification record (claim 5). 18_CBY_MONETARY OBS-CBY-00621 YER_USD_MARKET_RATE 2020-12 = 792.69 and OBS-CBY-00657 2023-12 = 1529.4 (SRC-CBY-001); 14_SYSTEM_CHRONOLOGY 2019 event: dual exchange rates between old and new notes across the divided monetary areas."
REM = "23_REMITTANCES: 2018–2024 period_state=HISTORICAL_REPORTED, calculation_state=SOURCE_REPORTED__IMF_STAFF_CALCULATIONS, series_vintage=2025_ARTICLE_IV_STAFF_REPORT; 2025–2030 series_vintage=2025_ARTICLE_IV_SUPPLEMENTARY_REVISION (SRC-IMF-AIV-2025-SUPP-001)."

def S(pid, lead, pri, old, new, lang, ctype, basis, reason, down="Regenerate every listed Master cell; page_specs.json; search_index.json; dist EN/AR",
      search="Index text updates on regeneration", ia="none", vis="none", rights="none", val=None, sheets=None, rows=None, fields=None,
      expect=None, sem="yes", status="SPEC_PENDING_EXECUTION"):
    return dict(pid=pid, lead=lead, pri=pri, op="SUBSTR", old=old, new=new, lang=lang, ctype=ctype, basis=basis, reason=reason,
                down=down, search=search, ia=ia, vis=vis, rights=rights,
                val=val or "After regeneration the old string occurs 0 times in Master, projections and dist; the new string renders on every listed surface; public-literal closure passes.",
                sheets=sheets, rows=rows, fields=fields, expect=expect, sem=sem, status=status)

def C(pid, lead, pri, sheet, obj, field, cur, new, lang, ctype, basis, reason, down, val, sem="yes", op="CELL", search="none", ia="none", vis="none", rights="none", status="SPEC_PENDING_EXECUTION"):
    return dict(pid=pid, lead=lead, pri=pri, op=op, sheet=sheet, obj=obj, field=field, cur=cur, new=new, lang=lang, ctype=ctype,
                basis=basis, reason=reason, down=down, search=search, ia=ia, vis=vis, rights=rights, val=val, sem=sem, status=status)

P2 = [
 # ---------------- LEAD-B08 (NEW BLOCKER): unconfirmed OECD/INFE Yemen scores and ranking --------------
 S("PB-0101", "LEAD-B08", "P2",
   "Separately, the OECD/INFE 2023 survey reports a financial well-being score of 15/100 for Yemen and an overall financial-literacy score of 42/100.",
   "Separately, the OECD/INFE 2023 adult financial-literacy survey, which covered 1,000 respondents in Yemen between 11 March and 1 April 2023, reports a financial well-being score of 15 out of 100 for Yemen and an overall financial-literacy score of 42 out of 100.",
   "en", "BOUNDARY_TIGHTENING", VER_OECD,
   "Acceptance correction A: the scores are verified; the sentence now carries the survey's own scope (sample and fieldwork) so the two values are read as survey measures of that sample, not as population rates."),
 S("PB-0102", "LEAD-B08", "P2",
   "وبشكل منفصل، يسجل مسح OECD/INFE لعام 2023 لليمن 15 من 100 في الرفاه المالي و42 من 100 في النتيجة الإجمالية للثقافة المالية.",
   "وبشكل منفصل، يسجل مسح OECD/INFE لعام 2023 للثقافة المالية لدى البالغين، الذي شمل في اليمن 1,000 مستجيب خلال الفترة من 11 مارس إلى 1 أبريل 2023، لليمن 15 من 100 في الرفاه المالي و42 من 100 في النتيجة الإجمالية للثقافة المالية.",
   "ar", "BOUNDARY_TIGHTENING", VER_OECD, "As PB-0101 (Arabic, co-authoritative)."),
 S("PB-0103", "LEAD-B08", "P2",
   "Do not attribute the 15/100 or 42/100 scores to Global Money Week activity",
   "Do not attribute any population capability measure to Global Money Week activity",
   "en", "BOUNDARY_TIGHTENING", VER_OECD, "Removes the unconfirmed scores from the prohibited-inference text while keeping the firewall.", status="SUPERSEDED|ACCEPTANCE_CORRECTION_A"),
 S("PB-0104", "LEAD-B08", "P2",
   "لا يجوز نسبة نتيجتي 15 من 100 أو 42 من 100 إلى أنشطة الأسبوع العالمي للمال",
   "لا يجوز نسبة أي قياس سكاني للقدرات المالية إلى أنشطة الأسبوع العالمي للمال",
   "ar", "BOUNDARY_TIGHTENING", VER_OECD, "As PB-0103.", status="SUPERSEDED|ACCEPTANCE_CORRECTION_A"),
 S("PB-0105", "LEAD-B08", "P2",
   "The OECD/INFE 2023 survey reports Yemen at 15 out of 100 for financial well-being and 42 out of 100 for overall financial literacy; Yemen has the lowest score among participating countries and economies on both measures. These scores add a capability and well-being lens to the people-side evidence. They sit alongside — rather than replace or combine with — Global Findex access measures, and neither is a percentage of people who are financially included.",
   "Account ownership is one dimension of financial inclusion; financial capability and financial well-being are others. In the OECD/INFE 2023 International Survey of Adult Financial Literacy, Yemen scored 42 out of 100 on overall financial literacy and 15 out of 100 on financial well-being. The Yemen survey covered 1,000 respondents interviewed by telephone and face to face between 11 March and 1 April 2023, and the report notes that the data were collected within a technical-assistance or regional project. These scores sit alongside — not replace or combine with — the Global Findex account-ownership measure, and neither is a percentage of people who are financially included.",
   "en", "BOUNDARY_TIGHTENING", VER_OECD,
   "Acceptance correction A: the two scores are verified and stay; the league-table sentence ('lowest among participating countries on both measures') is removed because no ranking is adopted (comparator policy) and it was not part of the verification; the survey scope and the technical-assistance note are added."),
 S("PB-0106", "LEAD-B08", "P2",
   "يسجل مسح OECD/INFE لعام 2023 لليمن 15 من 100 في الرفاه المالي و42 من 100 في النتيجة الإجمالية للثقافة المالية، وهي أدنى نتيجة بين البلدان والاقتصادات المشاركة في كلا المقياسين. وتضيف هاتان النتيجتان منظورًا للقدرات والرفاه إلى أدلة الأفراد، لكنهما لا تحلان محل مقاييس الوصول في Global Findex ولا تُدمجان معها في رقم واحد. كما أن أيًا منهما لا يمثل نسبة السكان المشمولين ماليًا.",
   "امتلاك الحساب بعدٌ واحد من أبعاد الشمول المالي، والقدرة المالية والرفاه المالي بعدان آخران. ففي المسح الدولي للثقافة المالية لدى البالغين الذي أجرته OECD/INFE عام 2023، سجل اليمن 42 من 100 في النتيجة الإجمالية للثقافة المالية و15 من 100 في الرفاه المالي. وشمل المسح في اليمن 1,000 مستجيب أُجريت مقابلاتهم هاتفيًا ووجهًا لوجه بين 11 مارس و1 أبريل 2023، ويشير التقرير إلى أن البيانات جُمعت في إطار مشروع للمساعدة الفنية أو مشروع إقليمي. وتبقى هاتان النتيجتان مكمّلتين لمقياس امتلاك الحساب في Global Findex، لا بديلًا عنه ولا قابلتين للدمج معه، ولا تمثل أي منهما نسبة السكان المشمولين ماليًا.",
   "ar", "BOUNDARY_TIGHTENING", VER_OECD, "As PB-0105."),
 C("PB-0107", "LEAD-B08", "P2", "03_PAGE_SECTIONS", "/people/ (r424 EN / r425 AR)", "section_role",
   "Current evidence || أدلة حديثة", "Evidence status || حالة الدليل", "both", "BOUNDARY_TIGHTENING", VER_OECD,
   "The eyebrow 'Current evidence' would label a withheld, unverified item as current evidence.", "dist /people/ eyebrow",
   "Eyebrow renders 'Evidence status' / «حالة الدليل».", status="SUPERSEDED|ACCEPTANCE_CORRECTION_A"),
 C("PB-0108", "LEAD-B08", "P2", "29_OECD_BENCHMARKS", "SCHEMA + r33 block header", "verification_state (new column) ; r33 label",
   "r33: 'Verified Yemen facts' (rows 35–51 carry no verification status)",
   "r33: 'Yemen values attributed to OECD sources — see verification_state'. New column verification_state for rows 35–51: OECD-YEM-001 (15/100 well-being) = CONFIRMED (OECD/INFE 2023 report, Figure 4.1; corroborated by OECD 2026 Promoting Economic Resilience in Yemen); OECD-YEM-002 (42/100 overall literacy) = CONFIRMED (OECD/INFE 2023 report, Figure 2.1; corroborated by OECD 2026); -003/-004/-005 (12%/11%/68%) = NOT_CONFIRMED__INSTRUMENT_AND_PERIOD_UNKNOWN; -006/-007 (605; 1,114) = NOT_VERIFIED_AGAINST_OECD_TEXT; -008 (YER 45bn) = SUBSTANCE_CONFIRMED_BY_INDEPENDENT_SOURCES__DECISION_NUMBER_UNVERIFIED (23-Mar-2022 decision); -009 (MFB YER 5bn) = SUBSTANCE_CONFIRMED_BY_INDEPENDENT_SOURCES; -010 (legal reserve 25%) = NOT_CONFIRMED; -011 (FCP instructions Aug-2023) = CONFIRMED (ref. 589, 20-Aug-2023; 'implementation still …' wording not verified); -012…-017 (SMEPS/YLG) = NOT_VERIFIED_AGAINST_OECD_TEXT. New row OECD-YEM-018, verification_state = CONFIRMED: 'In the OECD/INFE 2023 survey Yemen's data (sample 1,000; fieldwork 11 March–1 April 2023; telephone and face-to-face) were collected in the framework of technical assistance or regional projects; the coordinated 2022/23 financial-attitude score uses the two required attitude questions, the optional third being excluded' — basis: OECD/INFE 2023 report, Introduction and Annex A, source SRC-OECD-INFE-2023. Rows 35 and 36 english/arabic lose the unverified ranking clause (rows PB-0108.R1–R4). This row set is the Master basis for the public sentences installed by PB-0101, PB-0102, PB-0105 and PB-0106; execute PB-0108 before or with them.",
   "n/a", "SOURCE_CURRENTNESS_UPDATE", VER_OECD + " Claims 6–8 of the same record.",
   "The Master labels every row 'Verified' without a per-row state, and rows 35–36 carry an unverified league-table clause; per-row states make the verified values (001, 002, 011, 018) distinguishable from the rest.", "29_OECD_BENCHMARKS consumers; any generator reading 'Verified Yemen facts'",
   "No row with verification_state other than CONFIRMED may feed public copy."),
 C("PB-0109", "LEAD-B08", "P2", "29_OECD_BENCHMARKS", "rows 5–30 (Annex D table) and rows 54–62 (OECD diagnostic synthesis)", "publication status (new column public_use)",
   "No status; r6 'Global Average (39 Economies)' overall score 60.5; r59 'Female inclusion < 4% | Lowest female agency in household finance globally'; r61 'Decision No. (8/2022)'; r62 'Decision No. (9/2022)' and 25% legal reserve; r56–r62 carry 'OECD Recommended Reform & Strategic Action' text.",
   "public_use = NON_PUBLIC__PROVENANCE_DEFECT for rows 5–30 (60.5 contradicts the report's stated 60/100 average; country values unverified) and NON_PUBLIC__UNVERIFIED_LEAD_MATERIAL for rows 54–62 (unverified values; decision numbers 8/2022 and 9/2022 not located; recommendation text is not CauseWay or source-verified policy). Recommend removal from the Master at the next release into audit lineage.",
   "n/a", "BOUNDARY_TIGHTENING", VER_OECD + " Cross-cutting finding 2: '60.5' is a provenance screen.",
   "Latent: none of these values is public today (0 dist hits), but they sit in the sole authority with no status. r59 contradicts the governed 5.44% female account ownership.",
   "none today (0 public hits verified)", "Any future use of these rows must fail validation.", sem="yes"),
 C("PB-0110", "LEAD-B08", "P2", "28_METHODS_RIGHTS", "rows 43–68 (OECD/INFE Annex A item-level scoring)", "r44 header + public_use",
   "r44 control_note header: 'Verbatim Survey Question Prompt'", "r44: 'Question wording (reconstructed; not transcribed from the OECD/INFE toolkit)'; rows 43–68 public_use = NON_PUBLIC__RECONSTRUCTED_ITEMS",
   "n/a", "BOUNDARY_TIGHTENING", "Addendum §16 (OECD/INFE item-level integrity); rows are reconstructed paraphrases, not a transcription. Acceptance correction B: the scoring-summary block (rows 36–41) is verified OECD/INFE 2023 methodology — including r39, the coordinated 2022/23 attitude score built from the two required attitude questions with the optional third excluded — and is not quarantined; no alternative scoring battery is created.",
   "'Verbatim' is false for reconstructed items.", "none today (0 dist hits for 'Verbatim')", "No row 43–68 may feed public copy."),
 S("PB-0111", "LEAD-B08", "P2", "\n15/100 financial well-being\n42/100 financial literacy", "", "en", "BOUNDARY_TIGHTENING", VER_OECD,
   "Master cover sheet headline figures must not carry unconfirmed values.", sheets=["00_MASTER"], sem="yes", status="SUPERSEDED|ACCEPTANCE_CORRECTION_A"),
 S("PB-0112", "LEAD-B08", "P2", "605 licensed money exchangers (2014)\n1,114 money-exchange businesses (2022)",
   "2026 CBY-Aden roster: 98 exchange companies, 225 exchange establishments, 106 remittance agents (source category entries, not unique firms)",
   "en", "SOURCE_CURRENTNESS_UPDATE", "29_OECD_BENCHMARKS OECD-YEM-006/-007 not verified against OECD text; governed 2026 roster counts in 07 CLM-009.",
   "Replace unverified secondary counts on the Master cover with the governed current roster counts.", sheets=["00_MASTER"]),

 S("PB-0108.R1", "LEAD-B08", "P2", "Yemen scored 15 out of 100 in financial well-being, the lowest score among participating countries and economies.",
   "Yemen scored 15 out of 100 in financial well-being in the OECD/INFE 2023 survey (Figure 4.1).", "en", "SOURCE_CURRENTNESS_UPDATE", VER_OECD,
   "Keep the verified value; remove the unverified ranking clause from the Master basis row.", sheets=["29_OECD_BENCHMARKS"]),
 S("PB-0108.R2", "LEAD-B08", "P2", "سجل اليمن 15 من 100 في الرفاه المالي، وهي أدنى نتيجة بين البلدان والاقتصادات المشاركة.",
   "سجل اليمن 15 من 100 في الرفاه المالي في مسح OECD/INFE لعام 2023 (الشكل 4.1).", "ar", "SOURCE_CURRENTNESS_UPDATE", VER_OECD, "As PB-0108.R1.", sheets=["29_OECD_BENCHMARKS"]),
 S("PB-0108.R3", "LEAD-B08", "P2", "Yemen scored 42 out of 100 in overall financial literacy, lower than every other participating country and economy.",
   "Yemen scored 42 out of 100 in overall financial literacy in the OECD/INFE 2023 survey (Figure 2.1).", "en", "SOURCE_CURRENTNESS_UPDATE", VER_OECD, "As PB-0108.R1.", sheets=["29_OECD_BENCHMARKS"]),
 S("PB-0108.R4", "LEAD-B08", "P2", "سجل اليمن 42 من 100 في النتيجة الإجمالية للثقافة المالية، وهي أدنى من بقية البلدان والاقتصادات المشاركة.",
   "سجل اليمن 42 من 100 في النتيجة الإجمالية للثقافة المالية في مسح OECD/INFE لعام 2023 (الشكل 2.1).", "ar", "SOURCE_CURRENTNESS_UPDATE", VER_OECD, "As PB-0108.R1.", sheets=["29_OECD_BENCHMARKS"]),

 # ---------------- LEAD-B01 (RE-SEVERED BLOCKER→MATERIAL): nominal / USD / real; source term; CLM-054 downgrade ----------
 S("PB-0120", "LEAD-B01", "P2",
   "That source also reports 3.3 million active savers and about YER 44 billion in nominal portfolio in 2023, compared with verified 2020 anchors of 1.611 million savers/depositors and YER 33.379 billion. Because the 2023 primary object, set of providers covered by the evidence, saver definition and period bridge are unresolved, these values are separate bounded anchors—not a harmonized trend.",
   "That source also reports what it calls 3.3 million “active savers” and a nominal portfolio of about YER 44 billion in 2023. The verified 2020 anchors are 1.611 million savers/depositors and YER 33.379 billion; “active savers” and “savers/depositors” have not been shown to be the same measure. Both portfolio figures are nominal rials. Between December 2020 and December 2023 the average market rate published by the Central Bank in Aden moved from 792.69 to 1,529.4 rials per US dollar, and the evidence base does not record which rial valuation, across Yemen's divided monetary areas, the portfolio figures use. No real or US-dollar change can be derived from the two figures. With the 2023 primary source document, provider coverage, saver definition and period bridge also unresolved, these values are separate bounded anchors—not a trend.",
   "en", "BOUNDARY_TIGHTENING", FX + " Passport EP-MFB-SAVERS-2023-K04: 'Active savers/depositors — MFB source terminology'; EP-MFB-PORTFOLIO-2023-K04 critical_limit: no USD-comparable growth across currency regimes.",
   "Directive correction A: nominal, USD-equivalent and real are different concepts. The handover's 'FX-deflated −31.7%, sign reverses' is withdrawn: one CBY-Aden rate applied to a portfolio of unreported currency-area composition does not establish a US-dollar direction (the sign depends on that composition), and no price deflator is governed. 'Active' is the source's own term and is attributed, not deleted."),
 S("PB-0121", "LEAD-B01", "P2",
   "ويورد المصدر نفسه 3.3 مليون مدخر نشط ومحفظة اسمية تقارب 44 مليار ريال في 2023، مقابل 1.611 مليون مدخر/مودع ومحفظة قدرها 33.379 مليار ريال في 2020. ولأن الأصل الأولي لعام 2023 ونطاق مقدمي الخدمة وتعريف المدخرين والجسر الزمني لم تُحسم بالكامل، تُقرأ هذه القيم كنقاط مقيدة منفصلة لا كسلسلة اتجاه منسجمة.",
   "ويورد المصدر نفسه ما يسميه 3.3 مليون «مدخر نشط» ومحفظة اسمية تقارب 44 مليار ريال في 2023. أما النقاط المرجعية الموثقة لعام 2020 فهي 1.611 مليون مدخر/مودع ومحفظة قدرها 33.379 مليار ريال، ولم يثبت أن «المدخر النشط» و«المدخر/المودع» مقياس واحد. وقيمتا المحفظة اسميتان بالريال: فبين ديسمبر 2020 وديسمبر 2023 انتقل متوسط سعر الصرف في السوق الذي ينشره البنك المركزي في عدن من 792.69 إلى 1,529.4 ريال للدولار، ولا تسجل قاعدة الأدلة أساس التقييم بالريال الذي تستخدمه أرقام المحفظة في ظل انقسام المناطق النقدية في اليمن. لذلك لا يمكن استخلاص تغير حقيقي أو تغير بالدولار من هذين الرقمين. ومع بقاء الأصل الأولي لعام 2023 ونطاق مقدمي الخدمة وتعريف المدخرين والجسر الزمني دون حسم، تُقرأ هذه القيم كنقاط مرجعية منفصلة ومقيدة، لا كاتجاه واحد.",
   "ar", "BOUNDARY_TIGHTENING", FX, "As PB-0120."),
 S("PB-0122", "LEAD-B01", "P2",
   "The same secondary source reports 3.3 million active savers in 2023 and about YER44 billion in nominal portfolio, compared with verified 2020 anchors of 1.611 million savers/depositors and YER33.379 billion.",
   "The same secondary source reports what it calls 3.3 million “active savers” in 2023 and a nominal portfolio of about YER44 billion; the verified 2020 anchors are 1.611 million savers/depositors and YER33.379 billion. “Active savers” and “savers/depositors” have not been shown to be the same measure, and both portfolio figures are nominal rials: between December 2020 and December 2023 the average market rate published by the Central Bank in Aden moved from 792.69 to 1,529.4 rials per US dollar, and the evidence base does not record which rial valuation, across Yemen's divided monetary areas, the portfolio figures use, so no real or US-dollar change can be derived from them.",
   "en", "BOUNDARY_TIGHTENING", FX, "As PB-0120 (CLM-054 and its page projections)."),
 S("PB-0123", "LEAD-B01", "P2",
   "ويورد المصدر نفسه 3.3 مليون مدخر نشط في 2023 ومحفظة اسمية تقارب 44 مليار ريال، مقابل 1.611 مليون مدخر/مودع ومحفظة قدرها 33.379 مليار ريال في 2020.",
   "ويورد المصدر نفسه ما يسميه 3.3 مليون «مدخر نشط» في 2023 ومحفظة اسمية تقارب 44 مليار ريال، مقابل نقاط مرجعية موثقة لعام 2020 قدرها 1.611 مليون مدخر/مودع و33.379 مليار ريال. ولم يثبت أن «المدخر النشط» و«المدخر/المودع» مقياس واحد، وقيمتا المحفظة اسميتان بالريال: فبين ديسمبر 2020 وديسمبر 2023 انتقل متوسط سعر الصرف في السوق الذي ينشره البنك المركزي في عدن من 792.69 إلى 1,529.4 ريال للدولار، ولا تسجل قاعدة الأدلة أساس التقييم بالريال الذي تستخدمه أرقام المحفظة في ظل انقسام المناطق النقدية في اليمن، ولذلك لا يمكن استخلاص تغير حقيقي أو تغير بالدولار منهما.",
   "ar", "BOUNDARY_TIGHTENING", FX, "As PB-0122."),
 S("PB-0124", "LEAD-B01", "P2",
   "The 2024 secondary source reports 3.3 million active savers and about YER44 billion in nominal portfolio for 2023.",
   "The 2024 secondary source reports what it calls 3.3 million “active savers” and a nominal portfolio of about YER44 billion for 2023. “Active savers” and “savers/depositors” have not been shown to be the same measure, and the portfolio figures are nominal rials whose valuation across Yemen's divided monetary areas is not recorded in the evidence base, so no real or US-dollar change can be derived by comparing them.",
   "en", "READING_THESIS_REFINEMENT", FX, "CWR-006 supporting section."),
 S("PB-0125", "LEAD-B01", "P2",
   "ويورد المصدر الثانوي لعام 2023 نحو 3.3 ملايين مدخر نشط ومحفظة اسمية تقارب 44 مليار ريال.",
   "ويورد المصدر الثانوي المنشور في 2024 ما يسميه نحو 3.3 ملايين «مدخر نشط» ومحفظة اسمية تقارب 44 مليار ريال لعام 2023. ولم يثبت أن «المدخر النشط» و«المدخر/المودع» مقياس واحد، وقيم المحفظة اسمية بالريال ولا تسجل قاعدة الأدلة أساس تقييمها في ظل انقسام المناطق النقدية، ولذلك لا يمكن استخلاص تغير حقيقي أو تغير بالدولار من مقارنتها.",
   "ar", "READING_THESIS_REFINEMENT", FX + " Also fixes an AR/EN parity error: AR said the source is 'of 2023'; EN correctly says a 2024 source reporting 2023.",
   "As PB-0124; corrects publication-year vs reference-year parity."),
 S("PB-0126", "LEAD-B01", "P2", "this is a bounded directional signal—not a harmonized trend", "these are separate bounded anchors—not a trend",
   "en", "BOUNDARY_TIGHTENING", FX, "The saver and portfolio side cannot carry a direction; keep only separate anchors."),
 S("PB-0127", "LEAD-B01", "P2", "فهذه إشارة اتجاهية مقيدة وليست سلسلة اتجاه منسجمة", "فهذه نقاط مرجعية منفصلة ومقيدة، لا اتجاه واحد",
   "ar", "BOUNDARY_TIGHTENING", FX, "As PB-0126."),
 S("PB-0128", "LEAD-B01", "P2", "فهذه إشارة اتجاهية محدودة وليست سلسلة متجانسة", "فهذه نقاط مرجعية منفصلة ومقيدة، لا اتجاه واحد",
   "ar", "BOUNDARY_TIGHTENING", FX, "As PB-0126 (variant wording)."),
 S("PB-0129", "LEAD-B01", "P2",
   "Available evidence points to a divergence between borrower counts and reported saver/depositor and nominal-portfolio measures",
   "Borrower, saver and portfolio figures come from different sources and definitions and do not yet form one trend",
   "en", "BOUNDARY_TIGHTENING", FX, "CLM-054 headline asserted a divergence the saver/portfolio evidence cannot carry."),
 S("PB-0130", "LEAD-B01", "P2",
   "تشير الأدلة المتاحة إلى تباعد بين أعداد المقترضين ومقاييس المدخرين/المودعين والمحفظة الاسمية المبلغ عنها",
   "تأتي أرقام المقترضين والمدخرين والمحفظة من مصادر وتعريفات مختلفة، ولا تشكل بعدُ اتجاهًا واحدًا",
   "ar", "BOUNDARY_TIGHTENING", FX, "As PB-0129."),
 S("PB-0131", "LEAD-B01", "P2", "BOUNDED_DIRECTIONAL_DIVERGENCE", "SEPARATE_BOUNDED_ANCHORS", "n/a", "BOUNDARY_TIGHTENING",
   "07_PUBLIC_CLAIMS claim_type vocabulary.", "Claim type must match what the evidence supports. NEW controlled value; add to the claim-type vocabulary.",
   sheets=["07_PUBLIC_CLAIMS"], val="claim_type and evidence_badge of CLM-054 = SEPARATE_BOUNDED_ANCHORS; validator accepts the new value."),
 S("PB-0132", "LEAD-B01", "P2", "لا يجوز وصف هذا التباعد بأنه", "لا يجوز وصف هذه الأرقام بأنها", "ar", "BOUNDARY_TIGHTENING", FX, "Removes the asserted 'divergence' from the Arabic firewall."),
 S("PB-0133", "LEAD-B01", "P2", "and the available divergence does not establish improved borrower outcomes or causality.",
   "and these separate anchors do not establish improved borrower outcomes or causality.", "en", "BOUNDARY_TIGHTENING", FX, "/finance/ 'does not establish' section."),
 S("PB-0134", "LEAD-B01", "P2", "ولا يثبت التباعد المتاح تحسن نتائج المقترضين أو علاقة سببية.",
   "ولا تثبت هذه النقاط المنفصلة تحسن نتائج المقترضين أو علاقة سببية.", "ar", "BOUNDARY_TIGHTENING", FX, "As PB-0133."),
 S("PB-0135", "LEAD-B01", "P2",
   "Verified but bounded evidence points to a divergence: borrower counts do not rise in the same way as saver/depositor and nominal portfolio measures. The pattern is better described as divergence across distinct indicators than as a single story of 'growth' or 'deepening'.",
   "Borrower, saver and portfolio figures cannot yet be read as one story. Verified anchors record 93,118 active borrowers at end-2015 and 88,445 at end-2020, and a secondary source reports 78,686 for end-2023; with provider coverage and the period bridge unresolved, even these are anchors rather than a trend. The saver and portfolio figures use different definitions and are nominal rials whose valuation across Yemen's divided monetary areas is not recorded, so they cannot show whether saving or credit deepened. The evidence supports separate bounded anchors, not a story of 'growth', 'deepening' or 'divergence'.",
   "en", "READING_THESIS_REFINEMENT", FX + " Borrower anchors: 93,118 (end-2015), 88,445 (end-2020), 78,686 (end-2023, secondary).",
   "CWR-006 thesis rested on the saver/portfolio comparison that cannot bear a direction. Route slug /readings/microfinance-structural-divergence/ is retained for deep-link stability."),
 S("PB-0136", "LEAD-B01", "P2",
   "تشير الأدلة الموثقة والمتاحة ضمن حدودها إلى تباعد: لا ترتفع أعداد المقترضين بالطريقة نفسها التي تتحرك بها مقاييس المدخرين أو المودعين والمحفظة الاسمية. ويُوصف النمط بدقة أكبر كتباعد بين مؤشرات مختلفة، لا كقصة واحدة عن «النمو» أو «التعمق».",
   "لا يمكن بعدُ قراءة أرقام المقترضين والمدخرين والمحفظة بوصفها قصة واحدة. فالنقاط المرجعية الموثقة تسجل 93,118 مقترضًا نشطًا في نهاية 2015 و88,445 في نهاية 2020، ويورد مصدر ثانوي 78,686 لنهاية 2023؛ ومع بقاء نطاق مقدمي الخدمة والجسر الزمني دون حسم، تبقى هذه الأعداد نفسها نقاطًا مرجعية لا اتجاهًا. أما أرقام المدخرين والمحفظة فتستخدم تعريفات مختلفة، وهي قيم اسمية بالريال لا تسجل قاعدة الأدلة أساس تقييمها في ظل انقسام المناطق النقدية، فلا تكشف ما إذا كان الادخار أو الائتمان قد تعمق. وما تسنده الأدلة هو نقاط مرجعية منفصلة ومقيدة، لا قصة «نمو» أو «تعمق» أو «تباعد».",
   "ar", "READING_THESIS_REFINEMENT", FX, "As PB-0135."),
 S("PB-0137", "LEAD-B01", "P2", "Show divergence across distinct indicators without manufacturing a harmonized trend.",
   "Show the borrower, saver and portfolio anchors as separate dated points without manufacturing a trend or a divergence.",
   "en", "VISUAL_CONTRACT_REFINEMENT", FX, "RV-CWR-006 visual contract follows the refined thesis."),
 S("PB-0138", "LEAD-B01", "P2", "يُظهر التباعد بين مؤشرات مختلفة من دون تصنيع سلسلة زمنية موحدة.",
   "يعرض نقاط المقترضين والمدخرين والمحفظة كنقاط مؤرخة منفصلة من دون تصنيع اتجاه أو تباعد.", "ar", "VISUAL_CONTRACT_REFINEMENT", FX, "As PB-0137."),
 S("PB-0139", "LEAD-B01", "P2", "from divergent nominal/administrative series.", "from separate nominal and administrative anchors.",
   "en", "VISUAL_CONTRACT_REFINEMENT", FX, "As PB-0137.", fields=["prohibited_inference_en"]),
 S("PB-0140", "LEAD-B01", "P2", "Do not call the divergence broader inclusion", "Do not call these separate anchors broader inclusion",
   "en", "BOUNDARY_TIGHTENING", FX, "33_ANALYTICS_MASTER INS-K04-023 caveat aligned."),
 S("PB-0141", "LEAD-B01", "P2", "deduplicated saver object or real-value bridge materially changes interpretation.",
   "deduplicated saver measure, or a valuation bridge that states the portfolio's currency-area composition and a price basis, materially changes interpretation.",
   "en", "MEASUREMENT_SCOPE_REFINEMENT", FX, "States exactly what would allow a real or US-dollar comparison."),
 S("PB-0142", "LEAD-B01", "P2", "أو كائن للمدخرين منزوع الازدواج، أو جسر للقيم الحقيقية يغيّر التفسير بدرجة جوهرية.",
   "أو سجل موحد للمدخرين بعد إزالة التكرار، أو جسر للتقييم يبيّن توزيع المحفظة بين المناطق النقدية وأساسًا للأسعار، يغيّر التفسير بدرجة جوهرية.",
   "ar", "MEASUREMENT_SCOPE_REFINEMENT", FX, "As PB-0141; also removes the calques «كائن» and «منزوع الازدواج»."),

 # ---------------- LEAD-B02: leaked authoring instruction (EN and AR) ----------
 S("PB-0150", "LEAD-B02", "P2",
   "Use the documented system chronology as contextual navigation around Finance rather than as a long narrative block. Show only the events that materially help explain funding, liquidity, exchange-rate conditions, intermediation or payment infrastructure, and let users open the dated event record for source and limitations. Chronology is context, not a causal model of financial inclusion.",
   "The dated events below help explain the conditions under which finance operates: funding and liquidity pressures, exchange-rate conditions, intermediation and payment infrastructure. Each event opens a record with its source and limitations. The chronology is context, not a causal model of financial inclusion.",
   "en", "EDITORIAL_NO_SEMANTIC_CHANGE", "03_PAGE_SECTIONS r331 body_en: imperative instruction to authors, rendered publicly.", "Non-public authoring copy shipped to readers.", sem="no"),
 S("PB-0151", "LEAD-B02", "P2",
   "استخدم السلسلة الزمنية الموثقة بوصفها سياقًا قابلًا للاستكشاف حول صفحة التمويل، لا كتلة نصية طويلة. اعرض فقط الأحداث التي تساعد فعليًا على تفسير التمويل والسيولة وظروف سعر الصرف والوساطة أو بنية المدفوعات، مع إمكانية فتح سجل الحدث المؤرخ لرؤية المصدر وحدود الاستنتاج. التسلسل الزمني سياق، وليس نموذجًا سببيًا للشمول المالي.",
   "تساعد الأحداث المؤرخة أدناه على فهم الظروف التي يعمل فيها التمويل: ضغوط التمويل والسيولة، وأوضاع سعر الصرف، والوساطة المالية، وبنية المدفوعات. ويفتح كل حدث سجلًا يبين مصدره وحدود ما يثبته. والتسلسل الزمني سياق، وليس نموذجًا سببيًا للشمول المالي.",
   "ar", "EDITORIAL_NO_SEMANTIC_CHANGE", "03_PAGE_SECTIONS r332 body_ar: the same instruction in Arabic (not recorded by the prior window).", "As PB-0150.", sem="no"),

 # ---------------- LEAD-B03 (corrected by directive B): formal-credit magnitude shown separately, no ratio ----------
 S("PB-0160", "LEAD-B03", "P2",
   "The current evidence base does not yet contain a harmonized, publication-ready set of non-performing-loan, capital-adequacy and liquidity ratios with common definitions and vintages.",
   "The current evidence base does not yet contain a harmonized, publication-ready set of non-performing-loan, capital-adequacy and liquidity ratios with common definitions and vintages. For scale, the Central Bank's statistics (Aden) record bank credit to the private sector of YER 1,350.4 billion in May 2026. Since January 2023 foreign-currency positions have been valued at the market exchange rate, so movements in this series can reflect revaluation, not only lending.",
   "en", "BOUNDARY_TIGHTENING", "18_CBY_MONETARY BANK_CREDIT_PRIVATE_SECTOR_BN_YER 2026-05 = 1350.4 (SRC-CBY-001); 03 r317 documents the January-2023 market-rate valuation shift.",
   "The page covers formal finance and microfinance (binding correction #2) yet gives no formal-credit magnitude. The magnitude is published on its own, with its valuation caveat."),
 S("PB-0161", "LEAD-B03", "P2",
   "ولا تتضمن القاعدة الحالية بعد مجموعة منسجمة وجاهزة للنشر لمؤشرات القروض المتعثرة وكفاية رأس المال والسيولة بتعريفات ونسخ زمنية قابلة للمقارنة.",
   "ولا تتضمن القاعدة الحالية بعد مجموعة منسجمة وجاهزة للنشر لمؤشرات القروض المتعثرة وكفاية رأس المال والسيولة بتعريفات ونسخ زمنية قابلة للمقارنة. وللتوضيح بالأرقام، تسجل إحصاءات البنك المركزي في عدن ائتمانًا مصرفيًا للقطاع الخاص قدره 1,350.4 مليار ريال في مايو 2026. ومنذ يناير 2023 تُقيَّم المراكز بالعملات الأجنبية بسعر الصرف السوقي، لذلك قد تعكس تحركات هذه السلسلة أثر إعادة التقييم لا الإقراض وحده.",
   "ar", "BOUNDARY_TIGHTENING", "As PB-0160.", "As PB-0160."),
 S("PB-0162", "LEAD-B03", "P2",
   "The underlying 2023 SFD/SMED primary source behind several secondary figures has been identified but is not yet available for direct verification.",
   "The underlying 2023 SFD/SMED primary source behind several secondary figures has been identified but is not yet available for direct verification. Microfinance portfolio figures are also not expressed here as a share of bank credit: twelve microfinance banks appear on the same CBY-Aden bank list, so the two stocks may overlap, and they differ in valuation basis, date and institutional coverage.",
   "en", "BOUNDARY_TIGHTENING", "Directive correction B; 03 r433: 12 of 26 listed banks are microfinance banks; passport EP-MFB-PORTFOLIO-2023-K04 'about/exceeding', Nov/end-2023.",
   "The handover's '≈2.6% of formal private-sector credit' ratio is REJECTED: overlap unresolved, valuation bases differ (post-2023 market valuation vs nominal secondary figure), dates and universes differ."),
 S("PB-0163", "LEAD-B03", "P2",
   "وقد حُدد المصدر الأولي لعام 2023 من SFD/SMED الذي تقف خلفه عدة أرقام ثانوية، لكنه لم يصبح متاحًا بعد للتحقق المباشر.",
   "وقد حُدد المصدر الأولي لعام 2023 من SFD/SMED الذي تقف خلفه عدة أرقام ثانوية، لكنه لم يصبح متاحًا بعد للتحقق المباشر. كما لا تُعرض محفظة التمويل الأصغر هنا كنسبة من الائتمان المصرفي: فاثنا عشر بنكًا للتمويل الأصغر مدرجة في قائمة البنوك نفسها الصادرة عن البنك المركزي في عدن، ما يعني احتمال تداخل الرصيدين، فضلًا عن اختلافهما في أساس التقييم والتاريخ ونطاق المؤسسات المشمولة.",
   "ar", "BOUNDARY_TIGHTENING", "As PB-0162.", "As PB-0162."),

 # ---------------- /finance/ OECD-review assertion (never read) ----------
 S("PB-0165", "LEAD-B08", "P2",
   "The OECD financial-sector review reports product-holding and mobile-access measures that use questions and constructs different from the Global Findex account-ownership measure. They therefore remain separate evidence rather than a harmonised series.",
   "Product-holding and mobile-access figures attributed to the OECD's 2026 financial-sector review have not yet been verified against the review's own text, and they are not shown here. Any such measures would in any case use questions and constructs different from the Global Findex account-ownership measure and would remain separate evidence rather than a harmonised series.",
   "en", "BOUNDARY_TIGHTENING", VER_OECD + " Claim 3: 12%/11%/68% NOT CONFIRMED (U-09 open). Re-adjudicated at execution: this row withholds the unverified figures and asserts nothing that depends on the pending text, so it executes; U-09 stays open.",
   "The page asserts what an unread report 'reports'."),
 S("PB-0166", "LEAD-B08", "P2",
   "يعرض استعراض OECD للقطاع المالي مقاييس لحيازة بعض المنتجات المالية وللوصول إلى الهاتف المحمول، وهي مبنية على أسئلة ومفاهيم تختلف عن مقياس امتلاك الحساب في Global Findex. ولذلك تُعرض هذه المقاييس كأدلة منفصلة، لا كسلسلة موحدة.",
   "لم يُتحقق بعد من أرقام حيازة المنتجات المالية والوصول إلى الهاتف المحمول المنسوبة إلى استعراض OECD للقطاع المالي لعام 2026 مقابل نصه الأصلي، ولذلك لا تُعرض هنا. وأي مقاييس من هذا النوع تقوم في كل الأحوال على أسئلة ومفاهيم تختلف عن مقياس امتلاك الحساب في Global Findex، فتبقى أدلة منفصلة لا سلسلة موحدة.",
   "ar", "BOUNDARY_TIGHTENING", VER_OECD, "As PB-0165."),

 # ---------------- LEAD-B06: remittances evidence state and vintage splice ----------
 S("PB-0170", "LEAD-B06", "P2", "Remittances — observed history vs outlook", "Remittances — IMF-reported history, estimate and projections", "en", "BOUNDARY_TIGHTENING", REM,
   "'Observed' upgrades a HISTORICAL_REPORTED, staff-calculated series."),
 S("PB-0171", "LEAD-B06", "P2", "الحوالات: تاريخ مرصود مقابل التوقعات", "الحوالات: التاريخ الوارد في تقارير صندوق النقد والتقدير والتوقعات", "ar", "BOUNDARY_TIGHTENING", REM, "As PB-0170."),
 S("PB-0172", "LEAD-B06", "P2",
   "The series treats 2018–2024 as observed history, including US$1,861.7 million in 2024; 2025 is an estimate at US$1,977 million, while 2026–2030 are projections rising from US$2,159 million to US$3,110 million. Estimated and projected values are visually distinct from observations, and the series is not a measure of informal hawala volume.",
   "The IMF's 2025 Article IV staff report gives 2018–2024 as reported history based on staff calculations, including US$1,861.7 million in 2024. A later supplement to the same consultation gives US$1,977 million as the 2025 estimate and projections rising from US$2,159 million in 2026 to US$3,110 million in 2030. The two documents are different vintages, so the line breaks between 2024 and 2025. Estimates and projections are not observations, and the series is not a measure of informal hawala volume.",
   "en", "BOUNDARY_TIGHTENING", REM, "Names the evidence state correctly and makes the two-document splice visible."),
 S("PB-0173", "LEAD-B06", "P2",
   "تعامل السلسلة 2018–2024 كتاريخ مرصود، بما في ذلك 1,861.7 مليون دولار في 2024؛ أما 2025 فهو تقدير قدره 1,977 مليون دولار، وتمثل 2026–2030 توقعات ترتفع من 2,159 مليون دولار إلى 3,110 ملايين دولار. تُعرض القيم المقدرة والمتوقعة بوضوح منفصلة عن الرصد الفعلي، كما أن السلسلة لا تقيس حجم الحوالات غير الرسمية.",
   "يورد تقرير خبراء صندوق النقد الدولي لمشاورات المادة الرابعة لعام 2025 قيم 2018–2024 بوصفها تاريخًا مبلغًا عنه يستند إلى حسابات خبراء الصندوق، ومنها 1,861.7 مليون دولار في 2024. ثم يورد ملحق لاحق للمشاورات نفسها تقديرًا قدره 1,977 مليون دولار لعام 2025، وتوقعات ترتفع من 2,159 مليون دولار في 2026 إلى 3,110 ملايين دولار في 2030. ولأن الوثيقتين نسختان مختلفتان، ينقطع الخط بين 2024 و2025. والتقديرات والتوقعات ليست مشاهدات فعلية، كما أن السلسلة لا تقيس حجم الحوالات غير الرسمية.",
   "ar", "BOUNDARY_TIGHTENING", REM, "As PB-0172."),
 S("PB-0174", "LEAD-B06", "P2", "What is observed in remittance inflows, and what is only estimated or projected?",
   "What does the IMF report for past remittance inflows, and what is only estimated or projected?", "en", "VISUAL_CONTRACT_REFINEMENT", REM, "Visual question aligned with evidence state."),
 S("PB-0175", "LEAD-B06", "P2", "ما الذي رُصد من تدفقات الحوالات، وما الذي يظل تقديرًا أو توقعًا؟",
   "ما الذي يورده صندوق النقد عن تدفقات الحوالات السابقة، وما الذي يظل تقديرًا أو توقعًا؟", "ar", "VISUAL_CONTRACT_REFINEMENT", REM, "As PB-0174."),
 S("PB-0176", "LEAD-B06", "P2", "Observed 2018–24 is visually separate from 2025 estimate and 2026–30 projections.",
   "IMF-reported 2018–24 history is visually separate from the 2025 estimate and 2026–30 projections, with a break where the source document changes.",
   "en", "VISUAL_CONTRACT_REFINEMENT", REM, "As PB-0174."),
 S("PB-0177", "LEAD-B06", "P2", "يفصل بصريًا بين القيم المرصودة خلال 2018–2024، وتقدير 2025، وتوقعات 2026–2030.",
   "يفصل بصريًا بين القيم الواردة في تقارير الصندوق للفترة 2018–2024، وتقدير 2025، وتوقعات 2026–2030، مع انقطاع عند تغير الوثيقة المصدر.",
   "ar", "VISUAL_CONTRACT_REFINEMENT", REM, "As PB-0176."),
 S("PB-0178", "LEAD-B06", "P2",
   "Separates observed 2018–2024 remittance values from the 2025 estimate and 2026–2030 projections so forecast changes are not mistaken for observed change.",
   "Separates IMF-reported 2018–2024 values from the 2025 estimate and 2026–2030 projections, and keeps the two IMF documents apart, so forecast changes are not mistaken for economic change.",
   "en", "VISUAL_CONTRACT_REFINEMENT", REM, "As PB-0174."),
 S("PB-0179", "LEAD-B06", "P2", "يمنع قراءة تغيرات التقدير أو التوقع باعتبارها تغيرات اقتصادية مرصودة، ويحافظ على نسخة السلسلة وفترتها.",
   "يمنع قراءة تغيرات التقدير أو التوقع باعتبارها تغيرات اقتصادية فعلية، ويُبقي وثيقتي الصندوق منفصلتين مع نسخة كل منهما وفترتها.",
   "ar", "VISUAL_CONTRACT_REFINEMENT", REM, "As PB-0178."),
 S("PB-0180", "LEAD-B06", "P2", "2018–2030 with observed/estimate/projection states",
   "2018–2030: reported history (staff report) / estimate and projections (supplement)", "en", "VISUAL_CONTRACT_REFINEMENT", REM, "Freshness profile names the two documents."),
 S("PB-0181", "LEAD-B06", "P2", "IMF series; observed/estimate/projection status by year",
   "IMF external-sector remittance series; evidence state and source document by year", "en", "VISUAL_CONTRACT_REFINEMENT", REM, "Universe/denominator field."),
 S("PB-0182", "LEAD-B06", "P2", "سلسلة صندوق النقد المعتمدة للتحويلات، مع حالة كل سنة بوصفها مرصودة أو مقدرة أو متوقعة.",
   "سلسلة صندوق النقد للتحويلات في القطاع الخارجي، مع حالة كل سنة ووثيقة مصدرها.", "ar", "VISUAL_CONTRACT_REFINEMENT", REM, "As PB-0181."),
 S("PB-0183", "LEAD-B06", "P2", "Line with observed, estimate and projection states visibly distinct by label and line treatment.",
   "Line with reported-history, estimate and projection states visibly distinct by label and line treatment; the line breaks at the 2024→2025 change of source document and both documents are labelled.",
   "en", "VISUAL_CONTRACT_REFINEMENT", REM, "Encoding contract renders the vintage break (as the product already does for the e-money universe break)."),
 S("PB-0184", "LEAD-B06", "P2", "يُعرض خط زمني يميز بوضوح، بالوسم ونمط الخط، بين القيم المرصودة والتقديرات والتوقعات.",
   "يُعرض خط زمني يميز بوضوح، بالوسم ونمط الخط، بين القيم التاريخية المبلغ عنها والتقديرات والتوقعات، وينقطع الخط عند تغير الوثيقة المصدر بين 2024 و2025 مع تسمية الوثيقتين.",
   "ar", "VISUAL_CONTRACT_REFINEMENT", REM, "As PB-0183."),
 S("PB-0185", "LEAD-B06", "P2", "Do not present forecast revisions as observed changes.",
   "Do not present forecast revisions as economic changes, and do not join the two IMF documents into one continuous line.", "en", "BOUNDARY_TIGHTENING", REM, "Prohibited inference covers the splice."),
 S("PB-0186", "LEAD-B06", "P2", "التقديرات والتوقعات ليست رصدًا، ومراجعة التوقع ليست تغيرًا فعليًا، والسلسلة ليست حجم الحوالات غير الرسمية.",
   "التقديرات والتوقعات ليست مشاهدات فعلية، ومراجعة التوقع ليست تغيرًا اقتصاديًا، ولا تُوصل وثيقتا الصندوق في خط واحد متصل، والسلسلة ليست حجم الحوالات غير الرسمية.",
   "ar", "BOUNDARY_TIGHTENING", REM, "As PB-0185."),
 S("PB-0187", "LEAD-B06", "P2", "TWO_SERIES_LINE__OBSERVED_VS_ESTIMATE_PROJECTION", "TWO_SERIES_LINE__REPORTED_HISTORY_VS_ESTIMATE_PROJECTION__VINTAGE_BREAK",
   "n/a", "VISUAL_CONTRACT_REFINEMENT", REM, "visual_form token aligned (controlled value).", sheets=["11_VISUAL_LIBRARY"]),
 S("PB-0188", "LEAD-B06", "P2", "Observed, estimated and projected values are different evidence states",
   "Reported history, estimates and projections are different evidence states", "en", "BOUNDARY_TIGHTENING", REM, "/remittances/ section heading."),
 S("PB-0189", "LEAD-B06", "P2", "القيم المرصودة والمقدرة والمتوقعة حالات مختلفة من الدليل",
   "القيم التاريخية المبلغ عنها والتقديرات والتوقعات حالات مختلفة من الأدلة", "ar", "BOUNDARY_TIGHTENING", REM, "As PB-0188."),
 S("PB-0190", "LEAD-B06", "P2",
   "The IMF series treats 2018–2024 as observed history, 2025 as an estimate and 2026–2030 as projections. The chart never extends the observed line through the forecast as if all years had the same status.",
   "The IMF staff report gives 2018–2024 as reported history based on staff calculations; a later supplement to the same consultation gives 2025 as an estimate and 2026–2030 as projections. The chart breaks the line where the source document changes and never extends reported history through the forecast as if all years had the same status.",
   "en", "BOUNDARY_TIGHTENING", REM, "/remittances/ body."),
 S("PB-0191", "LEAD-B06", "P2",
   "تعامل سلسلة صندوق النقد 2018–2024 كتاريخ مرصود، و2025 كتقدير، و2026–2030 كتوقعات. ولا يمد الرسم خط الرصد عبر التوقعات كما لو كانت السنوات كلها من الحالة نفسها.",
   "يورد تقرير خبراء صندوق النقد قيم 2018–2024 بوصفها تاريخًا مبلغًا عنه يستند إلى حسابات خبراء الصندوق، ويورد ملحق لاحق للمشاورات نفسها قيمة 2025 كتقدير وقيم 2026–2030 كتوقعات. وينقطع الخط في الرسم عند تغير الوثيقة المصدر، ولا يُمد التاريخ المبلغ عنه عبر التوقعات كما لو كانت السنوات كلها من الحالة نفسها.",
   "ar", "BOUNDARY_TIGHTENING", REM, "As PB-0190."),
 S("PB-0192", "LEAD-B06", "P2", "Observed values, estimates and projections remain separate", "Reported history, estimates and projections remain separate", "en", "BOUNDARY_TIGHTENING", REM, "CLM-007 headline."),
 S("PB-0193", "LEAD-B06", "P2", "المشاهدات والتقديرات والتوقعات تبقى منفصلة", "القيم التاريخية المبلغ عنها والتقديرات والتوقعات تبقى منفصلة", "ar", "BOUNDARY_TIGHTENING", REM, "As PB-0192."),
 S("PB-0194", "LEAD-B06", "P2",
   "The verified IMF series shows materially higher remittance inflows in 2024 than in 2018, while 2025 onward objects are estimates/projections and must be shown separately.",
   "The IMF staff report's history shows materially higher remittance inflows in 2024 than in 2018 (both values from the same document); the 2025 estimate and 2026–2030 projections come from a later supplement and must be shown separately.",
   "en", "BOUNDARY_TIGHTENING", REM, "CLM-007 copy: 'verified' and 'objects' removed; same-vintage basis of the 2018→2024 comparison made explicit."),
 S("PB-0195", "LEAD-B06", "P2",
   "تُظهر سلسلة صندوق النقد الموثقة في المنظومة تدفقات تحويلات أعلى بصورة جوهرية في 2024 مقارنة بعام 2018، بينما تُصنف قيم 2025 وما بعدها كتقديرات أو توقعات ويجب عرضها بصورة منفصلة.",
   "تُظهر البيانات التاريخية الواردة في تقرير خبراء صندوق النقد تدفقات تحويلات أعلى بصورة جوهرية في 2024 مقارنة بعام 2018 (والقيمتان من الوثيقة نفسها)، أما تقدير 2025 وتوقعات 2026–2030 فمصدرها ملحق لاحق ويجب عرضها بصورة منفصلة.",
   "ar", "BOUNDARY_TIGHTENING", REM, "As PB-0194."),
 S("PB-0196", "LEAD-B06", "P2", "OBSERVED_VS_OUTLOOK", "REPORTED_HISTORY_VS_OUTLOOK", "n/a", "BOUNDARY_TIGHTENING", REM,
   "CLM-007 claim_type (controlled value; add to vocabulary).", sheets=["07_PUBLIC_CLAIMS"]),

 # ---------------- LEAD-M01: CLM-008 EN/AR firewall parity + backend voice ----------
 S("PB-0200", "LEAD-M01", "P2",
   "The system controls a 26-row current CBY-Aden licensed-bank source list; list presence proves listing/licensing in that source, not operation.",
   "The current CBY-Aden list of licensed banks names 26 banks. Appearing on the list establishes listing or licensing in that source, not operation.",
   "en", "BOUNDARY_TIGHTENING", "07 CLM-008 copy_en.", "Backend voice ('The system controls', '26-row') in a public claim about the most politically sensitive list."),
 S("PB-0201", "LEAD-M01", "P2",
   "تتضمن الأدلة المعتمدة في المنظومة قائمة حالية صادرة عن البنك المركزي اليمني – عدن تضم 26 صفًا للبنوك المرخصة. ويثبت الظهور في القائمة حالة الإدراج أو الترخيص في ذلك المصدر، لا التشغيل الفعلي.",
   "تضم القائمة الحالية للبنوك المرخصة الصادرة عن البنك المركزي اليمني – عدن 26 بنكًا. ويثبت الظهور في القائمة حالة الإدراج أو الترخيص في ذلك المصدر، لا التشغيل الفعلي.",
   "ar", "BOUNDARY_TIGHTENING", "07 CLM-008 copy_ar.", "Removes «المنظومة» self-reference and the calque «صف»."),
 S("PB-0202", "LEAD-M01", "P3",
   "Do not infer active branches, products, market share or rail participation.",
   "Do not infer active branches, products, market share or payment-rail participation. Appearing on the list establishes listing or licensing in that source only; it does not establish operation, all branches, participation, or national coverage beyond the scope of the issuing authority.",
   "en", "BOUNDARY_TIGHTENING", "07 CLM-008 does_not_prove_ar carries the authority-scope clause «خارج نطاق سلطة المصدر»; does_not_prove_en lacks it.",
   "Co-authority parity break on the authority-scope firewall; English brought up to Arabic."),

 # ---------------- LEAD-M02: authority scope qualification ----------
 S("PB-0210", "LEAD-M02", "P2", "The official CBY 2026 roster", "The official CBY-Aden 2026 roster", "en", "BOUNDARY_TIGHTENING",
   "22_PROVIDERS_DATA regulator_scope = CBY_ADEN_SUPERVISION_LIST; SRC-CBY-EXCH-LIST-2026-001 is a CBY-Aden instrument.", "Unqualified 'official CBY' implies a single national authority."),
 S("PB-0211", "LEAD-M02", "P2", "القائمة الرسمية للبنك المركزي لعام 2026", "القائمة الرسمية للبنك المركزي اليمني – عدن لعام 2026", "ar", "BOUNDARY_TIGHTENING", "As PB-0210.", "As PB-0210."),
 S("PB-0212", "LEAD-M02", "P2", "القائمة الرسمية للبنك المركزي لعام 2025", "القائمة الرسمية للبنك المركزي اليمني – عدن لعام 2025", "ar", "BOUNDARY_TIGHTENING", "As PB-0210 (2025 roster, SRC-CBY-EXCH-LIST-2025-001).", "As PB-0210."),
 S("PB-0213", "LEAD-M02", "P2", "The official 2025 CBY roster", "The official 2025 CBY-Aden roster", "en", "BOUNDARY_TIGHTENING", "As PB-0212.", "As PB-0210."),
 S("PB-0214", "LEAD-M02", "P2",
   "The current CBY-Aden licensed-bank source contains 26 source-listed bank rows. Provider classification identifies 12 of those rows as microfinance banks from the source label.",
   "The current CBY-Aden list of licensed banks names 26 banks; 12 of them are classified as microfinance banks on the basis of their names in the source.",
   "en", "EDITORIAL_NO_SEMANTIC_CHANGE", "03 r433.", "Removes 'rows'/'provider classification' backend vocabulary.", sem="no"),
 S("PB-0215", "LEAD-M02", "P2",
   "تضم القائمة الحالية للبنوك المرخصة الصادرة عن البنك المركزي اليمني – عدن 26 صفًا مصرفيًا. وتحدد المنظومة 12 منها كبنوك تمويل أصغر استنادًا إلى تصنيف المصدر.",
   "تضم القائمة الحالية للبنوك المرخصة الصادرة عن البنك المركزي اليمني – عدن 26 بنكًا، منها 12 بنكًا مصنفة بنوكَ تمويل أصغر استنادًا إلى تسمياتها في المصدر.",
   "ar", "EDITORIAL_NO_SEMANTIC_CHANGE", "03 r434.", "Removes the calque «صف مصرفي» and the self-referent «المنظومة».", sem="no"),
 C("PB-0216", "LEAD-M02", "P2", "03_PAGE_SECTIONS", "/providers/ NEW section (insert as section_order 2; renumber later sections +1)", "heading_en/body_en/heading_ar/body_ar",
   "(absent — the 'two central-bank authorities' fact appears only in /data/ and /finance/ chronology)",
   "EN heading: Whose list is this? || EN body: The current provider lists and status decisions on this page come from instruments issued by the Central Bank of Yemen in Aden. Since 2016 central-bank authority has been divided, and some banks on the current list have addresses in Sana'a and Taiz in the source. Status under any other authority is not established here; this defines the scope of the evidence and is not a judgement about either authority. Absence from a CBY-Aden list does not show that a provider is unlicensed elsewhere, and presence on it does not show that a provider can operate across all of Yemen. || AR heading: قائمة مَن هذه؟ || AR body: تأتي القوائم الحالية لمقدمي الخدمات وقرارات حالتهم في هذه الصفحة من وثائق صادرة عن البنك المركزي اليمني في عدن. ومنذ 2016 انقسمت سلطة البنك المركزي، وترد لبعض البنوك في القائمة الحالية عناوين في صنعاء وتعز بحسب المصدر. ولا تثبت هذه الصفحة وضع أي جهة لدى سلطة أخرى؛ فهذا تحديد لنطاق الدليل وليس حكمًا على أي من السلطتين. وغياب جهة عن قائمة البنك المركزي في عدن لا يعني أنها غير مرخصة في مكان آخر، كما أن ورودها فيها لا يعني أنها قادرة على العمل في كل أنحاء اليمن.",
   "both", "BOUNDARY_TIGHTENING", "14_SYSTEM_CHRONOLOGY: 2016 relocation left two central-bank authorities; 22_PROVIDERS_DATA listed addresses (e.g. Al-Zubairy Street, Sana'a; Jamal Street, Taiz).",
   "Divided supervisory authority is undisclosed on the provider page; the scope statement is a universe definition, not a political statement.",
   "/providers/ page; search_index", "Section renders in both languages above the exchange-roster section.", op="NEW", ia="New in-page section only; no route change"),
 C("PB-0217", "LEAD-M02", "P2", "22_PROVIDERS_DATA", "SCHEMA", "issuing_authority, territorial_scope (new columns)",
   "(only regulator_scope, e.g. CBY_ADEN_SUPERVISION_LIST)", "Populate per row from the row's source_id: CBY-Aden instruments → issuing_authority = CBY_ADEN; SRC-YMN-* (network membership) → NONE__NON_REGULATORY_SOURCE; rows without a source → UNKNOWN. territorial_scope = SOURCE_JURISDICTION_AS_STATED (never national by default). Render both on every provider record.",
   "n/a", "BOUNDARY_TIGHTENING", "22_PROVIDERS_DATA regulator_scope values.", "Makes authority scope a first-class field rather than a phrase.", "providers_data.json; /providers/; provider evidence records",
   "Every provider record shows issuing authority and scope.", op="SCHEMA"),

 # ---------------- LEAD-M11 (upgraded: in the Master itself) ----------
 C("PB-0220", "LEAD-M11", "P2", "25_FINDEX_BASELINE", "rows 14–35 ('Attached analytical inputs — not verified public Findex aggregates')", "whole rows",
   "22 rows of an unverified parallel Yemen Findex table (e.g. national broad account 0.096, female 0.038, poorest-40 0.042, richest-60 0.132) that contradict the governed rows 5–10 (11.9 / 5.44 / 6.5 / 15.5).",
   "REMOVE from the Production Master; archive into audit lineage as NOT_ADMITTED__CONTRADICTS_GOVERNED_FINDEX. Regenerate findex_baseline.json without the block.",
   "n/a", "BOUNDARY_TIGHTENING", "25_FINDEX_BASELINE r14 label; values match the ungoverned 'Yemen_Empirical_Baseline_2022' export, not World Bank published aggregates.",
   "The sole authority holds a contradictory parallel set of the product's headline numbers; one careless export makes the headline contestable from the product's own file. Latent: 0 public hits verified.",
   "findex_baseline.json (/data/ route input)", "25_FINDEX_BASELINE contains only governed rows; findex_baseline.json has no 'Attached analytical inputs' block; dist unchanged.", op="ROWS_REMOVE"),
 C("PB-0221", "LEAD-M11", "P2", "30_FCS_CONTEXT", "whole sheet (rows 5–41)", "whole sheet",
   "FCS peer matrix with unsourced country values (Yemen total account ownership 0.096, formal 0.064, mobile 0.052; peer values for Somalia, Sudan, Afghanistan, Syria, Lebanon) and unsourced claims (e.g. exchangers facilitate 'over 80%' of domestic remittances, diaspora inflows '~$4-5 billion annually').",
   "REMOVE from the Production Master into audit lineage (NOT_ADMITTED__UNSOURCED_COMPARATOR). Any future peer comparison must follow audit/BENCHMARK_AND_COMPARATOR_POLICY.md with primary sources.",
   "n/a", "BOUNDARY_TIGHTENING", "30_FCS_CONTEXT contents; Yemen row contradicts governed 11.9%.", "Unsourced comparator data inside the authority; league-table risk (addendum §15, §23).",
   "none today (0 public hits for peer values)", "Sheet absent from Master; no projection references it.", op="ROWS_REMOVE"),

 # ---------------- YPCC institution type (AR) ----------
 S("PB-0230", "PARITY-YPCC", "P3", "مركز اليمن للمقاصة وتسوية المدفوعات", "الشركة اليمنية للمدفوعات والمقاصة", "ar", "BOUNDARY_TIGHTENING",
   "Master EN name: 'Yemen Payments and Clearing Company' (company). AR renders it as «مركز» (centre). Acceptance correction D: official CBY public material uses «الشركة اليمنية للمدفوعات والمقاصة» (YPCC); this is the verified public name for ordinary public use.",
   "Institution type mismatch between languages; the verified official public name replaces the calque. The exact legal registered name (founding instrument) is not needed by any public surface and is not claimed.",
   status="VERIFIED_BY_CLAUDE_TEAM"),
]
