# -*- coding: utf-8 -*-
"""P2(remaining)–P5 — people levels, measurement, parity, trust, IA, language sweeps."""
from pdefs_p2 import S, C

FDX = "25_FINDEX_BASELINE WB-FINDEX-OBS-2022-001..006: total 11.9, female 5.44, male 18.35, poorest-40 6.5, richest-60 15.5, primary-or-less 6.98 (percent of population 15+); 27_FINDEX_SUBGROUPS FSG-0004 = PUBLIC_SAME_WAVE_GAP_READY."
RF = "31_REFORMS_REGULATION FMIIP-RF-004/012/013/014/015/017 (SRC-WB-FMIIP-P180708): baselines Jan-2025 817 / 170 / 1,062,441 / 200,898 / 375,252 / 65; RF-004 target Jun-2030 1,021."

P3 = [
 # ---------------- LEAD-M05: /people/ levels before gaps; income gap; education level ----------
 S("PB-0300", "LEAD-M05", "P2", "A measured gender gap — not yet an explanation", "Measured gaps by sex and income — not yet explanations",
   "en", "BOUNDARY_TIGHTENING", FDX, "A percentage-point gap without levels understates severity (12.91pp reads like 50↔63, not 5.44↔18.35)."),
 S("PB-0301", "LEAD-M05", "P2", "فجوة مقاسة بين الرجال والنساء — من دون افتراض سببها", "فجوات مقاسة بحسب الجنس والدخل — من دون افتراض أسبابها",
   "ar", "BOUNDARY_TIGHTENING", FDX, "As PB-0300."),
 S("PB-0302", "LEAD-M05", "P2",
   "The same wave shows a measured male–female account-ownership gap of 12.91 percentage points. Because the comparison is within the same survey wave, the disparity can be described; its causes cannot be established from that difference alone. It is not a 2026 gender-gap estimate.",
   "In the same wave, 5.44% of women and 18.35% of men have an account — a difference of 12.91 percentage points. Adults in the richest 60% by household income (15.5%) and in the poorest 40% (6.5%) differ by about 9.0 percentage points. Among adults with primary education or less, 6.98% have an account; the matching figure for adults with more education is not in the evidence base, so no education gap is stated. Because each comparison is within one survey wave, the disparities can be described; their causes cannot be established from these differences alone, and they are not 2026 estimates.",
   "en", "BOUNDARY_TIGHTENING", FDX + " Precision rule: derived gaps carry the input precision (15.5−6.5 = 9.0, never 9.00). Brief §15: levels first; the 3.37× ratio is not foregrounded.",
   "Levels first, income gap added, education reported as a level only (PARTIAL_HOLD_FOR_COMPLETE_PAIR)."),
 S("PB-0303", "LEAD-M05", "P2",
   "تظهر الموجة نفسها فجوة مقاسة بين الرجال والنساء في امتلاك الحسابات تبلغ 12.91 نقطة مئوية. هذه مقارنة داخل الموجة نفسها، ولا تثبت سبب الفجوة، ولا يجوز تقديمها باعتبارها فجوة عام 2026.",
   "في الموجة نفسها تملك 5.44% من النساء و18.35% من الرجال حسابًا، بفارق 12.91 نقطة مئوية. ويبلغ الفارق بين البالغين في أغنى 60% بحسب دخل الأسرة (15.5%) وفي أفقر 40% (6.5%) نحو 9.0 نقاط مئوية. وتبلغ نسبة امتلاك الحساب 6.98% بين البالغين الذين لم يتجاوز تعليمهم المرحلة الابتدائية، بينما لا تتضمن قاعدة الأدلة الرقم المقابل لمن تلقوا تعليمًا أعلى، ولذلك لا تُذكر فجوة بحسب التعليم. وهذه مقارنات داخل موجة مسح واحدة: يمكن وصف الفروق، لكن لا يمكن استنتاج أسبابها منها وحدها، ولا تمثل تقديرات لعام 2026.",
   "ar", "BOUNDARY_TIGHTENING", FDX, "As PB-0302."),
 S("PB-0304", "LEAD-M05", "P2", "Within the same wave, the measured male–female gap is 12.91 percentage points.",
   "Within the same wave, 5.44% of women and 18.35% of men have an account, a difference of 12.91 percentage points; adults in the richest 60% and poorest 40% by household income (15.5% and 6.5%) differ by about 9.0 percentage points.",
   "en", "VISUAL_CONTRACT_REFINEMENT", FDX, "VIS-FINDEX-GAPS accessible summary (and its embedded copies) omitted the levels and the income gap its own contract requires ('show levels first; annotate gender and income gaps')."),
 S("PB-0305", "LEAD-M05", "P2", "وداخل الموجة نفسها تبلغ الفجوة المقاسة بين الرجال والنساء 12.91 نقطة مئوية.",
   "وداخل الموجة نفسها تملك 5.44% من النساء و18.35% من الرجال حسابًا، بفارق 12.91 نقطة مئوية؛ ويبلغ الفارق بين البالغين في أغنى 60% وأفقر 40% بحسب دخل الأسرة (15.5% و6.5%) نحو 9.0 نقاط مئوية.",
   "ar", "VISUAL_CONTRACT_REFINEMENT", FDX, "As PB-0304."),
 S("PB-0306", "LEAD-M05", "P5", "The latest representative measure in the system reports 11.9%", "The latest representative survey measure reports 11.9%",
   "en", "EDITORIAL_NO_SEMANTIC_CHANGE", "Backend voice inside the flagship sentence.", "'in the system' is repository voice.", sem="no"),
 S("PB-0307", "LEAD-M05", "P5", "The latest representative Findex measure available in the system reports", "The latest representative Findex measure available reports",
   "en", "EDITORIAL_NO_SEMANTIC_CHANGE", "As PB-0306.", "As PB-0306.", sem="no"),
 S("PB-0308", "LEAD-M05", "P5", "تسجل أحدث الأدلة السكانية الممثلة في المنظومة", "تسجل أحدث الأدلة السكانية الممثلة المتاحة",
   "ar", "EDITORIAL_NO_SEMANTIC_CHANGE", "«المنظومة» self-referent inside the flagship sentence.", "As PB-0306.", sem="no"),
 S("PB-0309", "LEAD-M05", "P2", "The 12.91 percentage-point gender gap does not establish its causes.",
   "The 12.91-point gender difference and the 9.0-point income difference do not establish their causes.", "en", "BOUNDARY_TIGHTENING", FDX, "'Does not establish' covers both measured gaps."),
 S("PB-0310", "LEAD-M05", "P2", "كما أن فجوة 12.91 نقطة مئوية بين الرجال والنساء لا تثبت أسبابها.",
   "كما أن فارق 12.91 نقطة بين الرجال والنساء وفارق 9.0 نقاط بين فئتي الدخل لا يثبتان أسبابهما.", "ar", "BOUNDARY_TIGHTENING", FDX, "As PB-0309."),
 # directive correction C — state the limitation, manufacture no precision
 S("PB-0311", "LEAD-M04", "P2", "Administrative counts of accounts, wallets, savers, transactions or devices cannot substitute for a weighted people-level measure.",
   "Administrative counts of accounts, wallets, savers, transactions or devices cannot substitute for a weighted people-level measure. No confidence intervals for these subgroup values are held in the evidence base, and none are calculated here, so small differences between subgroups should not be over-read.",
   "en", "BOUNDARY_TIGHTENING", "Directive correction C; 0 occurrences of 'confidence interval/standard error/95%/±' in the governed corpus; documented design: 1,000 respondents, ~23% population excluded, >¼ PSUs replaced.",
   "States the uncertainty limitation honestly. The handover's model-calculated SE≈2.78pp, p≈0.16 and ratio CI [2.24, 5.08] are NOT published (not produced with survey weights/design)."),
 S("PB-0312", "LEAD-M04", "P2", "ولا يجوز استخدام أعداد الحسابات أو المحافظ أو المدخرين أو المعاملات أو الأجهزة بدل قياس سكاني موزون للأشخاص.",
   "ولا يجوز استخدام أعداد الحسابات أو المحافظ أو المدخرين أو المعاملات أو الأجهزة بدل قياس سكاني موزون للأشخاص. ولا تتضمن قاعدة الأدلة فترات ثقة لقيم هذه الفئات، ولا تُحسب هنا، لذلك لا ينبغي تحميل الفروق الصغيرة بين الفئات أكثر مما تحتمل.",
   "ar", "BOUNDARY_TIGHTENING", "As PB-0311.", "As PB-0311."),
 S("PB-0313", "LEAD-M04", "P4", "US$3.42216 billion", "about US$3.42 billion", "en", "BOUNDARY_TIGHTENING",
   "Six significant figures on a restated BOP estimate manufactures precision.", "Precision rule (rounding changes a displayed number, so labelled semantic)."),
 S("PB-0314", "LEAD-M04", "P4", "3.42216 مليارات دولار", "3.42 مليار دولار تقريبًا", "ar", "BOUNDARY_TIGHTENING", "As PB-0313.", "As PB-0313."),

 # ---------------- LEAD-M03: MA-003 + new income-gap claim ----------
 C("PB-0320", "LEAD-M03", "P4", "10_MEASUREMENT_AGENDA", "MA-003 (r7)", "current_evidence_en",
   "A 12.91 percentage-point gender gap is measured within the same survey wave. Comparable current inclusion differences by age group and displacement status are not established in the controlled evidence, and the contribution of identity, device, income, geography, trust and household constraints to any measured disparity is not established.",
   "Within the same survey wave, account ownership differs by 12.91 percentage points between women (5.44%) and men (18.35%), and by about 9.0 percentage points between adults in the poorest 40% (6.5%) and the richest 60% (15.5%) by household income. Comparable current differences by age group and displacement status are not established in the evidence base, and the contribution of identity, device, income, geography, trust and household constraints to any measured disparity is not established.",
   "en", "MEASUREMENT_SCOPE_REFINEMENT", FDX, "MA-003 omitted the measured income-group difference. A measured comparison is not a causal mechanism (brief §16); the causal clause is kept.",
   "measurement_agenda.json; /measurement/; /people/", "MA-003 renders both measured differences with levels; guardrail unchanged."),
 C("PB-0321", "LEAD-M03", "P4", "10_MEASUREMENT_AGENDA", "MA-003 (r7)", "current_evidence_ar",
   "تقيس الموجة نفسها فجوة قدرها 12.91 نقطة مئوية بين النساء والرجال. أما الفروق الراهنة القابلة للمقارنة بحسب الفئة العمرية وحالة النزوح فلا تثبتها الأدلة المحكومة الحالية، كما لا تثبت مقدار إسهام الهوية أو الجهاز أو الدخل أو الجغرافيا أو الثقة أو قيود الأسرة في تفسير أي تفاوت مقاس.",
   "في موجة المسح نفسها يختلف امتلاك الحساب بين النساء (5.44%) والرجال (18.35%) بمقدار 12.91 نقطة مئوية، وبين البالغين في أفقر 40% (6.5%) وأغنى 60% (15.5%) بحسب دخل الأسرة بنحو 9.0 نقاط مئوية. أما الفروق الراهنة القابلة للمقارنة بحسب الفئة العمرية وحالة النزوح فلا تثبتها قاعدة الأدلة الحالية، كما لا تثبت مقدار إسهام الهوية أو الجهاز أو الدخل أو الجغرافيا أو الثقة أو قيود الأسرة في تفسير أي تفاوت مقاس.",
   "ar", "MEASUREMENT_SCOPE_REFINEMENT", FDX, "As PB-0320; also replaces «الأدلة المحكومة» (backend term).", "As PB-0320", "As PB-0320."),
 C("PB-0322", "LEAD-M03", "P4", "07_PUBLIC_CLAIMS + 06_EVIDENCE_OBJECTS", "CLM-061 (NEW; next free ID after CLM-060)", "all claim fields; mirrored evidence-object row",
   "(no public claim exists for the income-group gap although FSG-0004 = PUBLIC_SAME_WAVE_GAP_READY)",
   "claim_type: DERIVED_SAME_WAVE_GAP | evidence_badge: PRIMARY_SURVEY_PLUS_APPROVED_DERIVATION | headline_en: A measured income-group gap | headline_ar: فجوة مقاسة بين فئتي الدخل | copy_en: Within the same Findex observation, 15.5% of adults in the richest 60% by household income and 6.5% of adults in the poorest 40% have an account — a difference of about 9.0 percentage points. | copy_ar: ضمن موجة المؤشر العالمي للشمول المالي نفسها، تملك نسبة 15.5% من البالغين في أغنى 60% بحسب دخل الأسرة حسابًا، مقابل 6.5% من البالغين في أفقر 40%، أي بفارق يقارب 9.0 نقاط مئوية. | does_not_prove_en: Do not read the difference as an effect of income, or present it as a 2026 gap. Income groups are defined within Yemen, the survey frame excludes geography representing about 23% of the population, and the evidence base holds neither a confidence interval nor the unweighted base n for these groups (the displayed values are World Bank published anchors, which FSG-0004 permits). | does_not_prove_ar: لا يجوز قراءة الفارق بوصفه أثرًا للدخل، ولا تقديمه كفجوة لعام 2026. فئات الدخل معرّفة داخل اليمن، ويستبعد إطار المسح مناطق تمثل نحو 23% من السكان، ولا تتضمن قاعدة الأدلة فترات ثقة ولا حجم العينة غير الموزون لهاتين الفئتين (والقيم المعروضة تقديرات منشورة من البنك الدولي يسمح بها FSG-0004). | evidence_inputs: [\"28_FINDEX_OBS\",\"FSG-0004\",\"EP-FINDEX-2022-ACCOUNT\"] | public_routes: [\"/people\",\"/evidence/compare\"] | 06 source_dependencies: SRC-WB-FINDEX-AGG-2022; lineage_state BOUND_EXACT",
   "both", "MEASUREMENT_SCOPE_REFINEMENT", FDX, "A measured, publication-ready gap had no public claim; CLM-002 (gender) is the template.",
   "public_claims.json; evidence_objects.json; new route /evidence/CLM-061/; /people/; search_index", "New claim and evidence page render in both languages; public-literal closure resolves 15.5/6.5/9.0 to 25_FINDEX_BASELINE.", op="NEW",
   search="New searchable claim ('income gap', «فجوة الدخل»)"),

 # ---------------- MA-001 extension (binding correction #7) ----------
 C("PB-0325", "MA-001", "P4", "10_MEASUREMENT_AGENDA", "MA-001 (r5)", "affected_routes", "[\"/people\",\"/\",\"/explore\"]", "[\"/people\",\"/\",\"/explore\",\"/remittances\"]",
   "n/a", "CROSS_LINK_CHANGE", "Brief §21: extend MA-001 rather than create MA-011.", "The people-side baseline gap also governs current remittance receipt.",
   "measurement_agenda.json; /remittances/ bindings", "/remittances/ shows MA-001 as its measurement priority."),
 S("PB-0326", "MA-001", "P4", "Major payment-system and reform changes are more recent.",
   "Major payment-system and reform changes are more recent. The latest published people-level values for receiving domestic remittances, and through which channels, are from 2014; the 2021-wave microdata contain these questions, but weighted estimates have not yet been produced.",
   "en", "MEASUREMENT_SCOPE_REFINEMENT", "26_FINDEX_HISTORY 2014 domestic-remittance receipt/channel values; 24_FINDEX_CODEBOOK 2021-wave variables fin28/fin29_* held but weighted estimates not produced (VIS-FINDEX-FLOW-CHANNELS = HOLD_WEIGHTED_MICRODATA).", "Adds the remittance-receipt dimension to the existing priority.", sheets=["10_MEASUREMENT_AGENDA"]),
 S("PB-0327", "MA-001", "P4", "أما التغيرات المهمة في منظومة المدفوعات والإصلاحات فهي أحدث من ذلك.",
   "أما التغيرات المهمة في المدفوعات والإصلاحات فهي أحدث من ذلك. كما تعود أحدث القيم المنشورة على مستوى الأفراد بشأن تلقي الحوالات المحلية وقنواتها إلى 2014؛ وتتضمن البيانات الفردية لموجة 2021 هذه الأسئلة، لكن التقديرات الموزونة لم تُنتج بعد.",
   "ar", "MEASUREMENT_SCOPE_REFINEMENT", "As PB-0326.", "As PB-0326.", sheets=["10_MEASUREMENT_AGENDA"]),
 S("PB-0328", "MA-001", "P4", "New representative Yemen demand-side survey or equivalent approved microdata with weights and clear coverage.",
   "New representative Yemen demand-side survey or equivalent approved microdata with weights and clear coverage, including remittance receipt, channel and frequency.",
   "en", "MEASUREMENT_SCOPE_REFINEMENT", "As PB-0326.", "As PB-0326.", sheets=["10_MEASUREMENT_AGENDA"]),
 S("PB-0329", "MA-001", "P4", "مسح تمثيلي جديد للطلب في اليمن، أو بيانات فردية موزونة ومعتمدة ذات تغطية واضحة.",
   "مسح تمثيلي جديد للطلب في اليمن، أو بيانات فردية موزونة ومعتمدة ذات تغطية واضحة، يشمل تلقي الحوالات وقنواته وتكراره.",
   "ar", "MEASUREMENT_SCOPE_REFINEMENT", "As PB-0326.", "As PB-0326.", sheets=["10_MEASUREMENT_AGENDA"]),
 S("PB-0330", "MA-001", "P5", "The latest representative people-side inclusion anchor available in the system predates",
   "The latest representative people-side inclusion anchor available predates", "en", "EDITORIAL_NO_SEMANTIC_CHANGE", "Backend voice.", "As PB-0306.", sem="no"),

 # ---------------- LEAD-M08: FMIIP dated baselines (supporting disclosure) + sheet structure ----------
 S("PB-0340", "LEAD-M08", "P4", "None by itself proves full operational go-live, reliability, user adoption, transaction coverage or an inclusion effect.",
   "None by itself proves full operational go-live, reliability, user adoption, transaction coverage or an inclusion effect. The project's results framework also records January-2025 baselines for its own project-defined indicators: 817 financial access points (2030 target: 1,021), 1,062,441 active bank accounts (200,898 of them owned by women), 375,252 active e-wallet accounts, 170 merchants accepting electronic payments and 65 agents of licensed financial institutions. These are project baselines that count access points, accounts, merchants and agents — not people — and they have not been reconciled with the central bank's payment-report totals or with survey measures of account ownership.",
   "en", "BOUNDARY_TIGHTENING", RF + " Zero-valued baselines (RF-001/005/006/007/008/010/011/019–024) are deliberately NOT published: they add no decision value and invite the rejected 'baseline zero → no use' reading (binding correction #3).",
   "Held but unpublished dated baselines; 1,021 is never shown without 817."),
 S("PB-0341", "LEAD-M08", "P4", "ولا يثبت أي منها بذاته بدء التشغيل الكامل أو الاعتمادية أو تبني المستخدمين أو تغطية المعاملات أو أثرًا على الشمول.",
   "ولا يثبت أي منها بذاته بدء التشغيل الكامل أو الاعتمادية أو تبني المستخدمين أو تغطية المعاملات أو أثرًا على الشمول. ويسجل إطار نتائج المشروع كذلك خطوط أساس في يناير 2025 لمؤشراته المعرّفة داخل المشروع: 817 نقطة وصول مالي (المستهدف في 2030: 1,021)، و1,062,441 حسابًا مصرفيًا نشطًا (منها 200,898 حسابًا مملوكًا لنساء)، و375,252 حساب محفظة إلكترونية نشطًا، و170 تاجرًا يقبلون المدفوعات الإلكترونية، و65 وكيلًا لمؤسسات مالية مرخصة. وهذه خطوط أساس للمشروع تعدّ نقاط الوصول والحسابات والتجار والوكلاء، لا الأشخاص، ولم تُطابق مع مجاميع تقارير المدفوعات لدى البنك المركزي ولا مع قياسات امتلاك الحساب في المسوح.",
   "ar", "BOUNDARY_TIGHTENING", RF, "As PB-0340."),
 C("PB-0342", "LEAD-M08", "P4", "31_REFORMS_REGULATION", "rows 80–103 (FMIIP-RF-001…024)", "column schema",
   "The sheet holds two tables with different schemas: regulatory events under the header in row 5, and the FMIIP results framework under its own title (row 78) and header (row 79: metric_id, indicator_en, indicator_ar, baseline_period, baseline_value, target_period, …). The block is correctly labelled in the Master, but any reader that uses the sheet-level header (row 5) mis-reads rows 80–103.",
   "No sheet move. The Master deliberately stores titled blocks, each with its own header row, inside a sheet (33 such blocks in 12 sheets; inventory in PB-0473). The rebuilt generator must read this block by its title (row 78) and header (row 79), never by the sheet header in row 5 (PB-0473). No value changes.",
   "n/a", "BOUNDARY_TIGHTENING", "31_REFORMS_REGULATION rows 78–79 (block title and header) and 80–103; independent verification corrected this window's initial 'misaligned' reading.", "Two schemas in one sheet are a mis-read risk for any generator (this window's own first export mis-read it).",
   "reforms_regulation.json", "Generator reads baseline/target from the block header; values unchanged.", op="GENERATOR_RULE"),

 # ---------------- LEAD-M10 (directive correction D): make incompatibility explicit, no imported denominator ----------
 C("PB-0345", "LEAD-M10", "P4", "03_PAGE_SECTIONS", "/evidence/compare/ NEW section (section_order 2)", "heading_en/body_en/heading_ar/body_ar",
   "(absent)",
   "EN heading: Three numbers that cannot be combined || EN body: Three figures are often set side by side. 11.9% is the share of adults (15+) in the survey's covered areas who had an account in the 2021 Findex wave, with fieldwork in 2022–23. About 3.3 million is what a 2024 secondary source calls “active savers” with microfinance providers in 2023 — relationships with providers, not deduplicated people. 1,062,441 active bank accounts and 375,252 active e-wallet accounts are project baselines for January 2025 — accounts, not people. They measure different things, over different populations and dates, from different kinds of evidence. They cannot be added, subtracted, ranked or converted into one another, and no population total is applied here to turn the counts into shares. For these three, “not comparable” is the correct result. || AR heading: ثلاثة أرقام لا يصح الجمع بينها || AR body: تُوضع ثلاثة أرقام جنبًا إلى جنب كثيرًا. فنسبة 11.9% هي حصة البالغين (15 سنة فأكثر) في المناطق التي غطاها المسح ممن كان لديهم حساب في موجة Findex 2021، التي نُفذ عملها الميداني خلال 2022–2023. ونحو 3.3 ملايين هو ما يسميه مصدر ثانوي منشور في 2024 «مدخرين نشطين» لدى مؤسسات التمويل الأصغر في 2023، وهي علاقات مع مقدمي خدمات لا أشخاص بعد إزالة التكرار. أما 1,062,441 حسابًا مصرفيًا نشطًا و375,252 حساب محفظة إلكترونية نشطًا فهي خطوط أساس لمشروع في يناير 2025، أي حسابات لا أشخاص. وهذه الأرقام تقيس أشياء مختلفة، لمجتمعات وتواريخ مختلفة، ومن أنواع مختلفة من الأدلة؛ فلا يجوز جمعها أو طرحها أو ترتيبها أو تحويل بعضها إلى بعض، ولا يُستخدم هنا أي عدد للسكان لتحويل الأعداد إلى نسب. والنتيجة الصحيحة في هذه الحالة هي «غير قابلة للمقارنة».",
   "both", "BOUNDARY_TIGHTENING", FDX + " " + RF + " Passport EP-MFB-SAVERS-2023-K04. Directive correction D: no adult denominator is imported.",
   "The three most-cited magnitudes are published with no statement of why they cannot be reconciled. The handover's 'publish an adult denominator' is REJECTED (correction D).",
   "/evidence/compare/; search_index", "Section renders in both languages; contains no population denominator and no derived sum.", op="NEW"),

 # ---------------- LEAD-M12: firms constraint list ----------
 S("PB-0350", "LEAD-M12", "P2", "The chart answers “what was cited as a general challenge in this survey?”",
   "Respondents could name more than one challenge, so the shares add up to more than 100%, and the base for this question is not recorded in the evidence base; small differences between adjacent items should not be read as a firm ranking. The chart answers “what was cited as a general challenge in this survey?”",
   "en", "BOUNDARY_TIGHTENING", "20_FIRM_FINANCE FFM-007: denominator_n empty; 16 challenge items sum to 300%, and the eight shown on the page sum to 242%.",
   "Multiple response and missing base not stated; adjacent 1–5 point differences presented as an order. (The Tranche A audit's 'access to finance ranks 6th' is withdrawn; it never reached public copy.)"),
 S("PB-0351", "LEAD-M12", "P2", "هذه النتائج تخص عينة المسح وجغرافيته، ولا تمثل ترتيبًا وطنيًا لجميع منشآت اليمن.",
   "وكان بإمكان المنشأة ذكر أكثر من تحدٍّ، لذلك يتجاوز مجموع النسب 100%، ولا تتضمن قاعدة الأدلة حجم العينة التي أجابت عن هذا السؤال؛ فلا ينبغي قراءة الفروق الصغيرة بين البنود المتجاورة كترتيب ثابت. وهذه النتائج تخص عينة المسح وجغرافيته، ولا تمثل ترتيبًا وطنيًا لجميع منشآت اليمن.",
   "ar", "BOUNDARY_TIGHTENING", "As PB-0350.", "As PB-0350.", rows=[("03_PAGE_SECTIONS", 337)]),

 # ---------------- Reading parity: CWR-010 (intra-Master) and CWR-001 (CCY unit error) ----------
 S("PB-0360", "CWR-010", "P3", "A successful cash payment is not yet durable financial use: Yemen evidence can support several links",
   "World Bank/G2Px documents a Yemen UCT digital-payment pilot in eight districts benefiting 45,460 recipients, with payments designed around fully functional accounts and recipient choice. This strengthens the evidence for the intermediate 'financial exposure' stage. It does not show whether recipients kept using the account or wallet after the programme-driven transaction.\n\nA successful cash payment is not yet durable financial use: Yemen evidence can support several links",
   "en", "READING_THESIS_REFINEMENT", "09_READING_SECTIONS r87 (CWR-010 supporting_evidence) holds this paragraph; 03_PAGE_SECTIONS r450 (the rendered page) omits it.",
   "The Reading's only direct-source paragraph was dropped from the rendered page. Structural fix: reading pages are generated from 09_READING_SECTIONS (see PB-0470).",
   rows=[("03_PAGE_SECTIONS", 450)]),
 S("PB-0361", "CWR-010", "P3", "نجاح الدفع النقدي لا يعني بعدُ استخدامًا ماليًا مستدامًا: تسمح الأدلة المتاحة",
   "يوثق البنك الدولي/مبادرة G2Px تجربة يمنية للمدفوعات الرقمية ضمن برنامج التحويلات النقدية غير المشروطة في ثماني مديريات استفاد منها 45,460 مستفيدًا، مع تصميم الدفع حول حسابات كاملة الوظائف وإتاحة الاختيار للمستفيد. يقوي ذلك الدليل على مرحلة وسيطة هي «التعرض لخدمة مالية». لكنه لا يبين ما إذا كان المستفيدون واصلوا استخدام الحساب أو المحفظة بعد المعاملة المرتبطة بالبرنامج.\n\nنجاح الدفع النقدي لا يعني بعدُ استخدامًا ماليًا مستدامًا: تسمح الأدلة المتاحة",
   "ar", "READING_THESIS_REFINEMENT", "As PB-0360.", "As PB-0360.", rows=[("03_PAGE_SECTIONS", 450)]),
 S("PB-0362", "CWR-001", "P3", "Do not declare a winning level; do not use 1.838 or 33% as universal conversion; do not call E&O hidden remittance; do not promote CCY 7.4bn to baseline.",
   "No single series is the correct level; no single scale factor — such as the roughly constant ratio of about 1.838 between the CBY and IMF remittance series, or the 33% population share the IMF used for areas administered from Aden — is a universal conversion; net errors and omissions are not hidden remittances; and the model estimate of at least US$7.4 billion by CCY (Cash Consortium of Yemen) is not a baseline.",
   "en", "BOUNDARY_TIGHTENING", "07 r45 does_not_prove_en ('remittance ~1.838 fingerprint', 'IMF 33% population allocation'); 03 r170 (CCY estimates at least USD 7.4 billion).",
   "Unexplained internal tokens (1.838, 33%, E&O, CCY) in reader copy; adds the unit and attribution the Arabic twin also fixes."),
 S("PB-0363", "CWR-001", "P3", "لا تختار المنظومة مستوىً «فائزًا» بين السلاسل غير المتكافئة، ولا تستخدم 1.838 أو 33% كمعامل تحويل عام، ولا تعامل بند الأخطاء والسهو كحوالات مخفية، ولا ترفع قيمة 7.4 مليار من العملة المحلية إلى خط أساس من دون سند منهجي.",
   "لا توجد سلسلة تمثل وحدها المستوى الصحيح؛ ولا يصلح معامل واحد — مثل النسبة الثابتة تقريبًا البالغة نحو 1.838 بين سلسلتي الحوالات لدى البنك المركزي وصندوق النقد، أو حصة السكان البالغة 33% التي استخدمها الصندوق للمناطق التي تديرها عدن — معاملَ تحويل عامًا؛ ولا يمثل صافي الأخطاء والسهو حوالات مخفية؛ ولا يُعتمد تقدير نموذج ائتلاف النقد في اليمن (CCY) البالغ 7.4 مليار دولار على الأقل خطَّ أساس.",
   "ar", "BOUNDARY_TIGHTENING", "03 r170 body_ar correctly says «7.4 مليارات دولار»; CWR-001 Arabic rendered 'CCY' as «من العملة المحلية» (local currency).",
   "SEMANTIC PARITY ERROR: wrong unit (local currency vs US dollars) and lost attribution in the Arabic Reading and its prohibited-inference field."),

 # ---------------- Trust surfaces ----------
 S("PB-0370", "TRUST-F01", "P3", "اختر من سجلين إلى أربعة. تبدأ المقارنة بالتعريف والفترة ومجتمع القياس والطريقة. عدم التطابق سبب لتقييد المقارنة لا لإخفائه.",
   "اختر من سجلين إلى أربعة. قارن التعريف والفترة ومجتمع القياس أو قاعدة الاحتساب والنطاق الجغرافي والوحدة والطريقة قبل مقارنة القيم. عدم التطابق سبب لتقييد المقارنة لا لإخفائها، وحين لا تتطابق التعريفات أو المجتمعات تكون «غير قابلة للمقارنة» نتيجة صحيحة.",
   "ar", "BOUNDARY_TIGHTENING", "03 r300: EN lists six compatibility dimensions; AR lists four (geography and unit missing).", "Parity break on the Compare tool's core instruction; adds F-02 'not comparable is a valid result'."),
 S("PB-0371", "TRUST-F02", "P3", "A mismatch is a reason to qualify the comparison, not to hide it.",
   "A mismatch is a reason to qualify the comparison, not to hide it; when definitions or populations do not match, “not comparable” is a valid result.",
   "en", "TRUST_COPY_REFINEMENT", "03 r300.", "F-02."),
 S("PB-0372", "TRUST-F05", "P5", "\nEvidence-backed public claims\n", "\n{N_CLAIMS} evidence-backed public claims\n",
   "en", "TRUST_COPY_REFINEMENT", "03 r79: the only inventory line without a count.", "F-05. {N_CLAIMS} is generated from 07_PUBLIC_CLAIMS at regeneration (59 today; 60 after PB-0322).", sheets=["03_PAGE_SECTIONS"]),
 S("PB-0373", "TRUST-F05", "P5", "\nادعاءات عامة مسندة بالأدلة\n", "\n{N_CLAIMS} خلاصة عامة مسندة بالأدلة\n",
   "ar", "TRUST_COPY_REFINEMENT", "As PB-0372; noun per the Arabic terminology decision (PB-0413).", "As PB-0372.", sheets=["03_PAGE_SECTIONS"]),
 C("PB-0374", "TRUST-F04", "P4", "06_EVIDENCE_OBJECTS", "SCHEMA", "limitations_en/ar → measurement_limitation_* + prohibited_inference_*",
   "Single 'limitations' field mixes measurement limits with prohibited inferences (pipe-merged in projections).",
   "Split into measurement_limitation_en/ar (what the measure cannot capture) and prohibited_inference_en/ar (what readers must not conclude). Populate by moving existing clauses; no new content.",
   "both", "BOUNDARY_TIGHTENING", "Handover trust review F-04.", "Readers need to see which limits are about the measure and which are about interpretation.",
   "evidence_objects.json; evidence pages 'Inference boundary' block", "Each evidence page shows both blocks; no clause lost (character-count parity before/after).", op="SCHEMA"),
 # rights (LEAD-M13)
 S("PB-0380", "LEAD-M13", "P2", "Every result keeps its definition, population or group covered, date, source, evidence state and reuse conditions with it.",
   "Every result keeps its definition, population or group covered, date, source and evidence state with it, and its reuse terms where they have been assessed.",
   "en", "TRUST_COPY_REFINEMENT", "15_SOURCE_LIBRARY: no rights field; source_reference_map rights_display_state = OBJECT_LEVEL_OR_UNSPECIFIED for 159/159.", "The page promises per-record rights no field can hold."),
 S("PB-0381", "LEAD-M13", "P2", "يحتفظ كل نتيجة بتعريفها، والمجتمع الذي تنطبق عليه، وتاريخها، ومصدرها، وحالة الدليل، وشروط إعادة الاستخدام.",
   "وتحتفظ كل نتيجة بتعريفها، والمجتمع الذي تنطبق عليه، وتاريخها، ومصدرها، وحالة الدليل، وبشروط إعادة الاستخدام حيثما جرى تقييمها.",
   "ar", "TRUST_COPY_REFINEMENT", "As PB-0380.", "As PB-0380; also fixes gender agreement («يحتفظ كل نتيجة» → «تحتفظ»)."),
 S("PB-0382", "LEAD-M13", "P2", "Availability tells you that the record can be displayed under its state and rights; it does not remove its methodological limits.",
   "Availability tells you that the record can be displayed; it does not tell you that the underlying data may be redistributed, and it does not remove its methodological limits.",
   "en", "TRUST_COPY_REFINEMENT", "As PB-0380.", "As PB-0380."),
 S("PB-0383", "LEAD-M13", "P2", "الإتاحة تعني أن عرضه مسموح وفق حالته وحقوقه، ولا تلغي حدوده المنهجية.",
   "الإتاحة تعني أن عرض السجل ممكن، لكنها لا تعني أن إعادة توزيع البيانات الأصلية مسموحة، ولا تلغي حدوده المنهجية.",
   "ar", "TRUST_COPY_REFINEMENT", "As PB-0380.", "As PB-0380."),
 S("PB-0384", "LEAD-M13", "P2", "Rights travel with the data", "Reuse terms belong to the original publisher", "en", "TRUST_COPY_REFINEMENT", "As PB-0380.", "As PB-0380.", sheets=["03_PAGE_SECTIONS"]),
 S("PB-0385", "LEAD-M13", "P2", "حقوق الاستخدام ترافق البيانات", "شروط إعادة الاستخدام تحددها الجهة الناشرة", "ar", "TRUST_COPY_REFINEMENT", "As PB-0380.", "As PB-0380.", sheets=["03_PAGE_SECTIONS"]),
 S("PB-0386", "LEAD-M13", "P2", "Some sources permit public display but not redistribution of the underlying table. Some permit source metadata while substantive values remain restricted. The same effective rule governs the website, search, Compare and any permitted download or export.",
   "Some sources permit public display but not redistribution of the underlying table; others permit source metadata while the values themselves remain restricted. Reuse terms have so far been assessed for only some sources. Where a source record does not state its terms, the original publisher's terms apply and should be checked before any redistribution. Including a source in this library does not mean CauseWay endorses its analysis or conclusions.",
   "en", "TRUST_COPY_REFINEMENT", "As PB-0380; brief §20 endorsement statement.", "As PB-0380."),
 S("PB-0387", "LEAD-M13", "P2", "تسمح بعض المصادر بالعرض العام لكنها لا تسمح بإعادة توزيع الجدول الأصلي، وقد تسمح مصادر أخرى ببيانات المصدر بينما تظل القيم نفسها مقيدة. وتطبق القاعدة الفعلية نفسها على الموقع والبحث والمقارنة وأي تنزيل أو تصدير مسموح به.",
   "تسمح بعض المصادر بالعرض العام لكنها لا تسمح بإعادة توزيع الجدول الأصلي، وتسمح مصادر أخرى ببيانات المصدر الوصفية بينما تظل القيم نفسها مقيدة. ولم تُقيَّم شروط إعادة الاستخدام حتى الآن إلا لبعض المصادر؛ وحيث لا يذكر سجل المصدر شروطه، تسري شروط الجهة الناشرة الأصلية ويجب التحقق منها قبل أي إعادة توزيع. كما أن إدراج مصدر في هذه المكتبة لا يعني أن CauseWay تتبنى تحليله أو استنتاجاته.",
   "ar", "TRUST_COPY_REFINEMENT", "As PB-0386.", "As PB-0386."),
 S("PB-0388", "LEAD-M13", "P2", "state/currentness, rights, limitations and correction history.", "state/currentness, reuse terms where recorded, limitations and correction history.",
   "en", "TRUST_COPY_REFINEMENT", "As PB-0380.", "As PB-0380."),
 S("PB-0389", "LEAD-M13", "P2", "وحداثة الدليل وحالته، وحقوق الاستخدام، والحدود، وسجل التصحيحات.", "وحداثة الدليل وحالته، وشروط إعادة الاستخدام حيثما سُجلت، والحدود، وسجل التصحيحات.",
   "ar", "TRUST_COPY_REFINEMENT", "As PB-0380.", "As PB-0380."),
 C("PB-0390", "LEAD-M13", "P2", "15_SOURCE_LIBRARY", "SCHEMA (all 159 rows)", "issuer, hosting_platform, rights_state, licence, attribution_requirement, retrieval_date (new columns)",
   "No rights columns; publisher empty on 133/159 rows (all public_card_state = LOCATOR_ONLY), including both IMF Article IV records and SRC-CBY-001; issuer, publisher and hosting platform are not distinguished.",
   "Add issuer, hosting_platform, rights_state (ASSESSED_OPEN | ASSESSED_RESTRICTED | NOT_ASSESSED), licence, attribution_requirement and retrieval_date. rights_state = NOT_ASSESSED on every row until the applicable terms are actually assessed (no row is promoted by this patch). issuer / hosting_platform stay empty unless confirmed from the source itself or authoritative metadata. Public rule (acceptance correction F): a verified public original locator may be shown for citation and verification while rights_state = NOT_ASSESSED; such a record offers no download, republication or reuse permission.",
   "n/a", "RESOURCE_METADATA_UPDATE", "15_SOURCE_LIBRARY publisher counts; 28_METHODS_RIGHTS rights rows; acceptance correction F (citation/linking is not redistribution permission; publisher is not inferred from a URL host).",
   "Rights layer exists in the Master but projects nowhere; issuer, publisher and host are conflated; LOCATOR_ONLY sources must be citable without implying reuse rights.",
   "source_library.json; source_reference_map.json; /data/ library; search facets", "Every source carries rights_state; no NOT_ASSESSED source is described as reusable or downloadable; locator-only records render the locator with the rights-not-assessed note.", op="SCHEMA",
   search="Rights state available as a facet", rights="Core rights projection"),
 C("PB-0390P", "LEAD-M13", "P2", "15_SOURCE_LIBRARY", "publisher / issuer on 133 LOCATOR_ONLY rows", "publisher, issuer (populate)",
   "publisher empty on 133/159 rows; audit/SOURCE_PUBLISHER_PROPOSALS.csv holds 104 candidate values derived from source-ID family and URL host, 29 unresolved.",
   "Populate publisher / issuer only where confirmed from the source itself or authoritative metadata; SOURCE_PUBLISHER_PROPOSALS.csv is a resolution aid, not metadata; unconfirmed rows stay empty.",
   "n/a", "RESOURCE_METADATA_UPDATE", "Acceptance correction F.", "Publisher values must be confirmed, not inferred from a host or ID family.",
   "source_library.json; source_reference_map.json", "Each populated value cites its confirmation basis.", op="SCHEMA", status="SOURCE_PENDING"),

 # ---------------- LEAD-M07: accessibility over-claim ----------
 C("PB-0400", "LEAD-M07", "P2", "GENERATOR: page_specs.json accessibility_requirements", "141/141 page specs", "tables_or_text_alternative_for_quantitative_visuals; visuals_must_expose_accessible_summary",
   "true on 141/141 while dist/ contains 0 <svg>, 0 <figure>, 0 <table>",
   "PENDING_DESIGN_IMPLEMENTATION on all specs until a rendered visual and its text alternative exist; add the text-alternative table contract (caption; scoped column/row headers; unit, population and period columns; source line) required independently of Design for any record carrying ≥3 quantities.",
   "n/a", "BOUNDARY_TIGHTENING", "dist/ element counts (this window): svg 0, figure 0, table 0.", "An unfalsifiable 'true' is an over-claim; honest state now, contract for later.",
   "page_specs.json; handoff DESIGN_TO_CODE_CONTRACT", "No spec asserts true without a rendered alternative; validator checks the contract once visuals exist.", sem="no", op="GENERATOR"),

 # ---------------- LEAD-B04 / LEAD-B05: meta description, strapline, Arabic 'claim' noun ----------
 C("PB-0410", "LEAD-B04", "P2", "scripts/build.py", "line 1224", "desc=",
   "desc=(spec.get('primary_user_question_internal') or '')[:180]",
   "desc=locv(spec,'meta_description',lang) or locv(spec,'title',lang)  — never render a *_internal field.",
   "both", "BOUNDARY_TIGHTENING", "dist: <meta name=description> on 141/141 EN and 141/141 AR pages is the English internal question; every spec's frontend_render_policy.never_render_directly lists '*_internal'.",
   "Breaches the product's own render policy; the Arabic edition's most public string (search snippets, link previews) is English.",
   "dist <head> on 282 pages", "0 pages render primary_user_question_internal; AR meta descriptions are Arabic.", sem="no", op="BUILD"),
 C("PB-0411", "LEAD-B04", "P2", "02_SITE_MAP", "SCHEMA", "meta_description_en / meta_description_ar (new columns)",
   "(absent)", "Governed per-language description; default rule at generation = title + first sentence of the first rendered section, ≤155 characters, in that language.",
   "both", "TRUST_COPY_REFINEMENT", "As PB-0410.", "The description must be governed copy, not an internal field.", "page_specs.json; dist <head>", "Every page has a non-empty description in its own language.", op="SCHEMA"),
 C("PB-0412", "LEAD-B05", "P3", "04_NAV_UX (new row UI-FOOTER-STRAPLINE) + scripts/build.py line 65", "footer strapline", "label_en / label_ar",
   "EN (build.py): Developed and maintained by CauseWay. A public resource linking claims to evidence and source. || AR (build.py): طوّرتها وتديرها CauseWay. مورد عام يربط الادعاء بالدليل والمصدر.",
   "EN: Developed and maintained by CauseWay. A public resource linking each claim to its evidence and original source. || AR: طوّرتها وتديرها CauseWay. مورد عام يربط كل خلاصة بدليلها ومصدرها الأصلي.  build.py renders the Master row instead of a hard-coded string.",
   "both", "TRUST_COPY_REFINEMENT", "build.py:65 (ungoverned). «الادعاء» in this collocation reads as 'the allegation' (forensic register); EN plural vs AR singular.",
   "The product's Arabic self-definition must be governed and natural.", "dist footer on 282 pages", "Footer renders the Master row in both languages.", op="NEW"),
 C("PB-0413", "LEAD-B05", "P3", "UMBRELLA — per-cell rows PB-0413.Snnn + PB-0413.T01 + PB-0413.B01–B03", "Arabic noun for a governed claim", "Arabic text",
   "Master (read from the .xlsx bytes): «ادعا…» occurs 65 times in 62 cells (02:15 cells, 03:16, 05:1, 06:9, 07:5 incl. the r1 sheet title, 09:12, 10:1, 11:3). Of the 65: 41 are the product's governed-claim noun; 24 carry the ordinary sense 'to assert / an assertion' (e.g. «من دون ادعاء إثباته»، «لا يجوز الادعاء بأن»). build.py UI strings: lines 65 (PB-0412), 535, 1089, 1154.",
   "41 claim-noun occurrences → «خلاصة / الخلاصات» (39 via per-cell rows PB-0413.Snnn on the post-patch text; 1 via PB-0373 in 03 r80; 1 via PB-0413.T01, the 07 sheet title). 24 assertion-sense occurrences KEEP, each listed with its rule in audit/TERMINOLOGY_SWEEP_KEEP_REGISTER.csv. build.py: PB-0413.B01–B03. Terminology basis: ARABIC_TERMINOLOGY_AND_STYLE_LEDGER.md §3.",
   "ar", "EDITORIAL_NO_SEMANTIC_CHANGE", "Arabic terminology decision (Lead), VERIFIED_BY_CLAUDE_TEAM, EXTERNAL_HUMAN_CERTIFICATION_NOT_PERFORMED. Count re-taken from the workbook bytes after the independent verifier's correction (earlier 64/61 omitted the 07 r1 title).",
   "In public Arabic «ادعاء» reads as 'allegation'; the product's governed statements are evidence-backed findings.", "All AR projections; dist AR; search_index AR",
   "Post-execution: «ادعا…» occurs exactly 24 times in public-bearing sheets, each at a KEEP-register locator; 0 in build.py UI strings.", sem="no", op="SWEEP_UMBRELLA", status="VERIFIED_BY_CLAUDE_TEAM|EXTERNAL_HUMAN_CERTIFICATION_NOT_PERFORMED"),
 C("PB-0413.T01", "LEAD-B05", "P3", "07_PUBLIC_CLAIMS", "sheet title (r1, above the header row)", "A1",
   "Public analytical claims / الادعاءات التحليلية العامة", "Public analytical claims / الخلاصات التحليلية العامة",
   "ar", "EDITORIAL_NO_SEMANTIC_CHANGE", "As PB-0413.", "Sheet title aligned with the public noun.", "none (sheet title is not rendered)", "A1 reads as proposed.", sem="no", op="CELL",
   status="VERIFIED_BY_CLAUDE_TEAM|EXTERNAL_HUMAN_CERTIFICATION_NOT_PERFORMED"),
 C("PB-0413.B01", "LEAD-B05", "P3", "scripts/build.py", "line 535 (Readings card on Home/Explore)", "AR string",
   "تحليل متعدد المصادر يبقى مربوطًا بالادعاءات والأدلة.", "تحليل متعدد المصادر يبقى مربوطًا بالخلاصات والأدلة.",
   "ar", "EDITORIAL_NO_SEMANTIC_CHANGE", "As PB-0413.", "UI string uses the public noun.", "dist AR pages carrying the card", "String renders as proposed.", sem="no", op="BUILD",
   status="VERIFIED_BY_CLAUDE_TEAM|EXTERNAL_HUMAN_CERTIFICATION_NOT_PERFORMED"),
 C("PB-0413.B02", "LEAD-B05", "P3", "scripts/build.py", "line 1089 (reference_intro)", "AR string",
   "وجودها في الدليل لا يرقّيها إلى نتيجة أو ادعاء.", "وجودها في الدليل لا يرقّيها إلى نتيجة أو خلاصة.",
   "ar", "EDITORIAL_NO_SEMANTIC_CHANGE", "As PB-0413.", "UI string uses the public noun.", "dist AR reference pages", "String renders as proposed.", sem="no", op="BUILD",
   status="VERIFIED_BY_CLAUDE_TEAM|EXTERNAL_HUMAN_CERTIFICATION_NOT_PERFORMED"),
 C("PB-0413.B03", "LEAD-B05", "P3", "scripts/build.py", "line 1154 (search placeholder)", "AR string",
   "ابحث في الادعاءات والأدلة والقراءات...", "ابحث في الخلاصات والأدلة والقراءات…",
   "ar", "EDITORIAL_NO_SEMANTIC_CHANGE", "As PB-0413.", "The most-seen Arabic UI string.", "dist AR header on 141 pages", "Placeholder renders as proposed.", sem="no", op="BUILD",
   status="VERIFIED_BY_CLAUDE_TEAM|EXTERNAL_HUMAN_CERTIFICATION_NOT_PERFORMED"),
 C("PB-0414", "ARABIC-SELFREF", "P5", "UMBRELLA — per-cell rows PB-0414.Snnn + PB-0414.B01–B02", "«المنظومة» as the product's self-referent", "Arabic text",
   "«منظومة/المنظومة» in public-bearing Master sheets is used both for the financial(-inclusion) system and as the product's own grammatical subject («لا تعرض المنظومة…»، «الموثقة في المنظومة»), so readers cannot tell which is meant. build.py lines 664 (renders 108×) and 1135.",
   "Lead decision: the product's self-referent becomes «المنصة» (feminine — every verb, pronoun and adjective agreement is preserved, so each edit is a one-word substitution); «منظومة» meaning the financial system is kept. Per-cell rows PB-0414.Snnn (post-patch text); KEEP occurrences with rule in audit/TERMINOLOGY_SWEEP_KEEP_REGISTER.csv. build.py: PB-0414.B01–B02.",
   "ar", "EDITORIAL_NO_SEMANTIC_CHANGE", "Arabic specialist wave; ARABIC_TERMINOLOGY_AND_STYLE_LEDGER.md §4.", "Repository voice in public Arabic; ambiguity with the financial system.", "All AR projections; dist AR",
   "Post-execution: every remaining «منظومة» is at a KEEP-register locator (financial-system sense).", sem="no", op="SWEEP_UMBRELLA", status="VERIFIED_BY_CLAUDE_TEAM|EXTERNAL_HUMAN_CERTIFICATION_NOT_PERFORMED"),
 C("PB-0414.B01", "ARABIC-SELFREF", "P5", "scripts/build.py", "line 664 (source_intro; renders on 108 evidence pages)", "AR string",
   "افتح سجل المصدر داخل المنظومة أو انتقل إلى الرابط الأصلي عندما تسمح حالة النشر بذلك.", "افتح سجل المصدر هنا، أو انتقل إلى الرابط الأصلي حين تسمح حالة النشر بذلك.",
   "ar", "EDITORIAL_NO_SEMANTIC_CHANGE", "As PB-0414.", "Highest-frequency self-referent in dist.", "dist AR /evidence/*/ (108 pages)", "String renders as proposed.", sem="no", op="BUILD",
   status="VERIFIED_BY_CLAUDE_TEAM|EXTERNAL_HUMAN_CERTIFICATION_NOT_PERFORMED"),
 C("PB-0414.B02", "ARABIC-SELFREF", "P5", "scripts/build.py", "line 1135 (corrections intro)", "AR / EN string",
   "لا تنشئ المنظومة سجل إصدارات أو تصحيحات افتراضيًا… || The product does not manufacture a release or correction history…",
   "لا تنشئ المنصة سجل إصدارات أو تصحيحات افتراضيًا… || This resource does not manufacture a release or correction history… (rest of both strings unchanged)",
   "both", "EDITORIAL_NO_SEMANTIC_CHANGE", "As PB-0414 / PB-0415.", "Self-referent in the corrections page.", "dist /corrections/ EN/AR", "Strings render as proposed.", sem="no", op="BUILD",
   status="VERIFIED_BY_CLAUDE_TEAM|EXTERNAL_HUMAN_CERTIFICATION_NOT_PERFORMED"),
 C("PB-0415", "ENGLISH-SELFREF", "P5", "UMBRELLA — per-cell rows PB-0415.Snnn", "'the system' / 'the product' / 'in the system' as the resource's self-referent", "English text",
   "e.g. 'The system does not plot 7→9→8…', 'The product separates them…', 'available in the system'. 'The system' is also used for the financial system, so the self-referent is ambiguous.",
   "Self-referent → 'this resource' / 'This resource'; 'available in the system' / 'in the system' → 'available here' / 'here'; 'The system's evidence' → 'The evidence here'. Financial-system and financial-product senses kept (KEEP register). Per-cell rows PB-0415.Snnn (post-patch text). build.py line 1135 via PB-0414.B02.",
   "en", "EDITORIAL_NO_SEMANTIC_CHANGE", "English specialist wave; ENGLISH_EDITORIAL_CLOSURE.md §2.", "Repository voice; ambiguity with the financial system.", "All EN projections; dist EN",
   "Post-execution: every remaining 'the system/the product' is at a KEEP-register locator.", sem="no", op="SWEEP_UMBRELLA"),

 # ---------------- LEAD-M09: IA (Option B family, no route change) ----------
 C("PB-0420", "LEAD-M09", "P5", "04_NAV_UX", "NAV-READINGS (item 3)", "label_en", "Readings", "Evidence Readings", "en", "IA_LABEL_CHANGE",
   "audit/CLAUDE_S01_IA_DECISION.md; AR already «قراءات الأدلة».", "EN/AR asymmetry; 'Readings' alone is not self-explanatory.", "navigation_interaction.json; header; drawer; breadcrumbs", "Header EN shows 'Evidence Readings'."),
 C("PB-0421", "LEAD-M09", "P5", "04_NAV_UX", "NAV-DATA (item 4)", "label_en / label_ar", "Data || البيانات", "Data & sources || البيانات والمصادر", "both", "IA_LABEL_CHANGE",
   "Footer already renders 'Data & sources'; header renders 'Data' (live contradiction).", "The route holds reports, sources, decisions and regulations, not only data.", "header; drawer; footer; breadcrumbs; search facet", "Header and footer labels identical."),
 C("PB-0422", "LEAD-M09", "P5", "04_NAV_UX", "NAV-METHODOLOGY (item 5)", "label_en / label_ar + children", "Methodology || المنهجية (no children)",
   "Navigation family 'Method & Measurement' || «المنهج والقياس» containing two equally important destinations: 'Methodology' «المنهجية» → /methodology/ and 'Measurement Agenda' «أجندة القياس» → /measurement/. Semantic requirements only (acceptance correction H): no route change; equal conceptual prominence; both destinations easily discoverable from the global header on desktop and mobile; keyboard accessible; no hover-only meaning; correct mobile and RTL behaviour; clear active state for either destination. The exact interaction treatment is left to Claude Design within these conditions.",
   "both", "IA_LABEL_CHANGE", "audit/CLAUDE_S01_IA_DECISION.md §1/§3 (Option B adjudicated; hard condition: two distinct destinations, equally weighted, each independently reachable); navigation_interaction.json has no children schema; aria-haspopup = 0.",
   "Executes the accepted Tranche A decision; makes the Measurement Agenda reachable from the header without a new route and without subordinating it to Methodology.", "navigation_interaction.json schema; header; drawer; /measurement/ breadcrumb parent",
   "Both destinations discoverable from the header on every page; neither subordinated to the other; keyboard reachable; no hover-only meaning; RTL order mirrored correctly; active state visible for either; re-run the 320–400px and RTL suite on the implemented treatment."),
 C("PB-0423", "LEAD-M09", "P5", "04_NAV_UX + navigation_interaction.json", "NAV-ABOUT (item 6); footer group method_measure; /measurement/ entry_modes", "placement",
   "About in primary nav; /about/ listed in footer group method_measure; /measurement/ navigation_prominence CONTEXTUAL_FOOTER",
   "Same commit: (a) add global_navigation to /measurement/ entry_modes and set prominence PRIMARY_CHILD; (b) move /about/ to a visible Trust group (About · Corrections · Rights & reuse · Accessibility · Privacy · Terms · Contact) shown in a prominent secondary position and the footer; the Arabic About label stays «عن الموقع» (acceptance correction G); (c) remove /about/ from method_measure regardless.",
   "both", "IA_LABEL_CHANGE", "As PB-0422.", "About must not be lost when demoted; Measurement must gain what About loses.", "header; footer; drawer", "About reachable from every page in one click; footer groups contain no misfiled route."),
 C("PB-0424", "LEAD-M09", "P5", "GENERATOR: navigation_interaction.json", "global_navigation schema", "children[]",
   "{route,label_en,label_ar}", "{route?,label_en,label_ar,children:[{route,label_en,label_ar}]}; validator: every child has a route; a grouping node without a route has ≥2 routed children; both children of the Method & Measurement family are present. Presentation (always-visible, disclosure, grouping) is not fixed by the schema (acceptance correction H).",
   "n/a", "IA_LABEL_CHANGE", "As PB-0422.", "Schema support for PB-0422.", "navigation_interaction.json; build.py header/drawer", "Validator passes the new rule.", op="SCHEMA"),

 # ---------------- Structural Master rules ----------
 C("PB-0470", "FULLCOPY-RULE", "P3", "02_SITE_MAP + 03_PAGE_SECTIONS + 09_READING_SECTIONS", "all routes", "full_copy_en/ar; reading page sections",
   "02_SITE_MAP.full_copy_* is authored separately and is not rendered by build.py; it is derivable from title + 03 sections on 257/282 cells and diverges on 25 (e.g. /finance/, /measurement/, all ten reading pages). Reading pages render 03_PAGE_SECTIONS, which diverge from the Reading object in 09_READING_SECTIONS (e.g. CWR-010).",
   "03_PAGE_SECTIONS is the canonical rendered copy for pages; 09_READING_SECTIONS is canonical for Readings and generates the reading pages' sections; 02_SITE_MAP.full_copy_* becomes a DERIVED field (title + rendered sections), never authored. Before regeneration, reconcile the 25 divergent cells: text present only in full_copy is either moved into sections (if intended public) or dropped.",
   "both", "BOUNDARY_TIGHTENING", "This window's derivation test over all 141 routes.", "Resolves the open constitution §5 item 'full-copy versus canonical-section relationships'; removes a parallel-truth vector.",
   "page_specs.json full_copy; search_index (if it indexes full_copy)", "full_copy_* equals the concatenation rule for 282/282 cells; reading pages equal 09 sections.", op="SCHEMA"),
 C("PB-0471", "EMBED-RULE", "P3", "03_PAGE_SECTIONS", "section bodies that embed object text", "body_en/body_ar",
   "Section bodies store verbatim copies of object text (visual accessible summaries, claim copy, key figures, badges) — e.g. r408 carries VIS-FINDEX-GAPS accessible_summary_en and CLM-002 copy_en.",
   "Embedded object blocks are generated from the owning object (06/07/11) at build time and are not stored in section cells. Until the generator exists, every object patch in this spec lists the embedding cells explicitly (this spec's SUBSTR rows already do).",
   "both", "BOUNDARY_TIGHTENING", "This window's cell scan (object sentences found inside 03 bodies).", "A parallel copy of object text inside pages guarantees drift.", "page_sections.json", "No object sentence is stored in a 03 cell after regeneration.", op="SCHEMA"),

 C("PB-0472", "FULLCOPY-RULE", "P2", "02_SITE_MAP", "/readings/microfinance-structural-divergence/ (Excel row 139)", "full_copy_en / full_copy_ar",
   "Divergent derived cell (one of the 25 whose full_copy is not title + sections). After every other patch in this spec it still carries pre-correction CWR-006 wording: 'points to a divergence' (EN ×2), 'reports 3.3 million active savers' without source attribution (EN ×1), «إلى تباعد» (AR ×2), «مدخر نشط» without guillemets (AR ×2).",
   "Regenerate both cells under PB-0470 (title + post-patch 09_READING_SECTIONS for CWR-006, in reading order). Do not hand-edit. The regenerated cells inherit PB-0120–PB-0147 wording.",
   "both", "BOUNDARY_TIGHTENING", "Simulation of this spec: 0 residual forbidden strings in rendered or public-bearing fields; 7 residual strings, all in this one non-rendered derived cell pair.",
   "The Master must not keep superseded wording in any cell, rendered or not.", "none rendered today (build.py does not render full_copy); page_specs.json full_copy fields",
   "After regeneration, the FORBID scan of this spec returns 0 across all Master cells, including 02 full_copy.", op="REGENERATE"),

 # ---------------- Small currentness precisions ----------
 S("PB-0480", "CURRENTNESS-FCP", "P5", "Financial Consumer Protection Regulatory Instructions were adopted in August 2023.",
   "Financial Consumer Protection Regulatory Instructions (reference 589) were issued by the Central Bank in Aden on 20 August 2023.",
   "en", "SOURCE_CURRENTNESS_UPDATE", "Verification record claim 5: instrument, title, reference 589, date 20-8-2023 and Aden seat CONFIRMED; SRC-CBY-FCP-INSTR-2023-001.", "Adds verifiable reference and seat."),
 S("PB-0481", "CURRENTNESS-FCP", "P5", "اعتمدت تعليمات تنظيمية لحماية المستهلك المالي في أغسطس 2023.",
   "أصدر البنك المركزي في عدن التعليمات التنظيمية لحماية المستهلك المالي (المرجع 589) في 20 أغسطس 2023.",
   "ar", "SOURCE_CURRENTNESS_UPDATE", "As PB-0480.", "As PB-0480."),
]

# Search (generator-level; search_index.json is generated)
P3_SEARCH = [
 C("PB-0490", "SEARCH-R", "P5", "GENERATOR: search_index.json", "source records", "index coverage",
   "158 of 159 source records indexed (SRC-MOPIC-YSEU-2023-080 missing); 132 LOCATOR_ONLY records invisible to search.",
   "Index all 159; surface LOCATOR_ONLY records with publisher and document type after PB-0390.", "both", "RESOURCE_METADATA_UPDATE",
   "Search specialist wave (R1–R13).", "Law/decision discovery fails when records are unindexed.", "search_index.json", "159 indexed; 'law' and «قانون» return legal instruments.", sem="no", op="GENERATOR"),
 C("PB-0491", "SEARCH-R", "P5", "GENERATOR: search_index.json", "evidence and claim records", "indexed fields",
   "does_not_establish / does_not_prove text is not indexed; no stemming (EN) or light normalisation (AR).",
   "Index does_not_prove_* and prohibited_inference_* as a separate low-weight field; add EN stemming and AR normalisation (hamza/ta-marbuta/alef variants, definite article). Reject a broad issuer-only alias; caveat the education↔literacy alias as discovery-only (never factual equivalence).",
   "both", "CROSS_LINK_CHANGE", "Search wave: 18/8/2 EN and 16/9/3 AR pass/weak/fail; two repository smoke tests fail at top-10.", "Discovery of boundaries and Arabic morphology.",
   "search_index.json; app.js search", "All nine repository smoke tests pass at top-10 in both languages.", sem="no", op="GENERATOR"),
]

# ---------------- Variants surfaced by the application simulation ----------------
from pdefs_p2 import FX
P3_VARIANTS = [
 S("PB-0143", "LEAD-B01", "P2",
   "The same secondary source reports 3.3 million active savers and about YER 44 billion in nominal portfolio in 2023, compared with verified 2020 anchors of 1.611 million savers/depositors and YER 33.379 billion. These values come from different evidence conditions and are shown as separate anchors, not one harmonized trend; they do not establish unique people or real credit deepening.",
   "The same secondary source reports what it calls 3.3 million “active savers” and a nominal portfolio of about YER 44 billion in 2023; the verified 2020 anchors are 1.611 million savers/depositors and YER 33.379 billion. The two saver measures are not shown to be the same, and the portfolio values are nominal rials across divided monetary areas, so the values are shown as separate anchors, not a trend; they do not establish unique people, real credit deepening or a US-dollar change.",
   "en", "VISUAL_CONTRACT_REFINEMENT", FX, "VIS-MFI-DIVERGENCE accessible summary (variant not listed in the handover)."),
 S("PB-0144", "LEAD-B01", "P2",
   "ويورد المصدر نفسه 3.3 مليون مدخر نشط ومحفظة اسمية تقارب 44 مليار ريال في 2023، مقابل 1.611 مليون مدخر/مودع ومحفظة قدرها 33.379 مليار ريال في 2020. تُعرض هذه القيم كنقاط منفصلة بسبب اختلاف شروط الدليل ولا تُربط في اتجاه منسجم؛ كما لا تثبت أشخاصًا فريدين أو تعمقًا حقيقيًا للائتمان.",
   "ويورد المصدر نفسه ما يسميه 3.3 مليون «مدخر نشط» ومحفظة اسمية تقارب 44 مليار ريال في 2023، مقابل نقاط مرجعية موثقة لعام 2020 قدرها 1.611 مليون مدخر/مودع و33.379 مليار ريال. ولم يثبت أن مقياسي المدخرين متطابقان، وقيم المحفظة اسمية بالريال عبر مناطق نقدية منقسمة؛ لذلك تُعرض كنقاط منفصلة لا كاتجاه، ولا تثبت أشخاصًا فريدين أو تعمقًا حقيقيًا للائتمان أو تغيرًا بالدولار.",
   "ar", "VISUAL_CONTRACT_REFINEMENT", FX, "As PB-0143."),
 S("PB-0145", "LEAD-B01", "P2", "so these are bounded directional signals rather than one continuous series.",
   "so these are separate bounded anchors rather than one continuous series.", "en", "READING_THESIS_REFINEMENT", FX, "CWR-006 supporting section variant."),
 S("PB-0146", "LEAD-B01", "P2", "لذلك تمثل هذه القيم إشارات اتجاهية مقيدة لا سلسلة مستمرة واحدة.",
   "لذلك تمثل هذه القيم نقاطًا مرجعية منفصلة ومقيدة لا سلسلة مستمرة واحدة.", "ar", "READING_THESIS_REFINEMENT", FX, "As PB-0145."),
 S("PB-0147", "LEAD-B01", "P4", "3.3 million active savers in 2023", "3.3 million “active savers” (source term) in 2023", "en", "EDITORIAL_NO_SEMANTIC_CHANGE", FX,
   "Passport keeps the source term but marks it as such.", sheets=["34_EVIDENCE_PASSPORTS"], sem="no"),
 S("PB-0218", "LEAD-M02", "P2", "the current CBY-Aden licensed-bank source contains 26 source-listed bank rows, 12 labelled in the provider register as microfinance banks",
   "the current CBY-Aden list of licensed banks names 26 banks, 12 of which are classified as microfinance banks on the basis of their names in the source", "en", "EDITORIAL_NO_SEMANTIC_CHANGE", "09 r51 / 03 r506.", "Backend vocabulary ('rows', 'provider register') in a Reading.", sem="no"),
 S("PB-0219", "LEAD-M02", "P2", "The current verified CBY-Aden licensed-bank source contains 26 source-listed bank rows; provider register classifies 12 as microfinance banks based on the source label.",
   "The current CBY-Aden list of licensed banks names 26 banks; 12 of them are classified as microfinance banks on the basis of their names in the source.", "en", "EDITORIAL_NO_SEMANTIC_CHANGE", "07 CLM-055 and projections.", "As PB-0218.", sem="no"),
 S("PB-0224", "LEAD-M02", "P2", "26 صفًا مصرفيًا مدرجًا في المصدر، يصنف سجل مقدمي الخدمات 12 منها كبنوك تمويل أصغر وفق تسمية المصدر",
   "26 بنكًا مدرجًا في المصدر، منها 12 بنكًا مصنفة بنوكَ تمويل أصغر استنادًا إلى تسمياتها في المصدر", "ar", "EDITORIAL_NO_SEMANTIC_CHANGE", "09 r51 / 03 r506.", "Removes the calque «صف مصرفي».", sem="no"),
 S("PB-0225", "LEAD-M02", "P2", "تضم القائمة الحالية المعتمدة في المنظومة للبنوك المرخصة الصادرة عن البنك المركزي اليمني – عدن 26 صفًا مصرفيًا، ويصنف سجل مقدمي الخدمات 12 منها كبنوك تمويل أصغر استنادًا إلى تسمية المصدر.",
   "تضم القائمة الحالية للبنوك المرخصة الصادرة عن البنك المركزي اليمني – عدن 26 بنكًا، منها 12 بنكًا مصنفة بنوكَ تمويل أصغر استنادًا إلى تسمياتها في المصدر.", "ar", "EDITORIAL_NO_SEMANTIC_CHANGE", "07 CLM-055 copy_ar and projections.", "As PB-0224.", sem="no"),
 S("PB-0315", "LEAD-M04", "P4", "USD 3.42216 billion", "about USD 3.42 billion", "en", "BOUNDARY_TIGHTENING", "As PB-0313 (spelling variant).", "Precision rule."),
]
P3 = P3 + P3_VARIANTS
